
import React, { createContext, useState, useContext, useMemo, useCallback, useEffect } from 'react';
import type { Language } from './types';

// Define theme type
export type Theme = 'light' | 'dark';

// Define the shape of the localization context
interface LocalizationContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
  dir: 'ltr' | 'rtl';
  theme: Theme;
  setTheme: (theme: Theme) => void;
}

// Translations object
const translations = {
  en: {
    // General
    loading: 'Loading...',
    close: 'Close',
    submit: 'Submit',
    save: 'Save',
    share: 'Share',
    printOrSave: 'Print / Download PDF',
    readMore: 'Read More',
    showLess: 'Show Less',
    viewDetails: 'View Details',
    back: 'Back',
    cancel: 'Cancel',
    talkWithUs: 'Talk with Us',
    actions: 'Actions',
    saveDraft: 'Save Draft',
    loadDraft: 'Load Draft',
    clearForm: 'Clear Form',
    draftSaved: 'Draft saved successfully!',
    draftLoaded: 'Draft loaded successfully!',
    formCleared: 'Form cleared!',
    confirmLoad: 'Are you sure you want to load the saved draft? This will overwrite any unsaved changes.',
    confirmClear: 'Are you sure you want to clear the form? All entered data will be lost.',
    foundSavedDraft: 'We found a saved draft. Would you like to load it?',
    confirmDeleteDocument: 'Are you sure you want to delete "{docName}"?',
    confirmDeleteItem: 'Are you sure you want to delete this item?',
    confirmDeleteShipment: 'Are you sure you want to delete shipment {id}?',
    confirmDeleteRoute: 'Are you sure you want to delete this route?',
    confirmDeleteUser: 'Are you sure you want to delete user {email}?',
    confirmDeleteArticle: 'Are you sure you want to delete this article?',
    confirmDeleteCompany: 'Are you sure you want to delete company {name}?',
    // App sections
    home: 'Home',
    articles: 'Articles',
    tools: 'Tools',
    knowledgeBase: 'Knowledge Base',
    directory: 'Directory',
    routePlanner: 'Route Planner',
    hsCodeFinder: 'HS Code Finder',
    invoiceGenerator: 'Invoice & Packing List',
    shippingForms: 'SD/FSD Forms',
    shipmentTracker: 'Your Shipments',
    documentEditor: 'Certificates',
    contactUs: 'Contact Us',
    profile: 'Profile',
    pricing: 'Pricing',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    faq: 'FAQ',
    // Footer Specific
    quickLinks: 'Quick Links',
    supportLegal: 'Support & Legal',
    aboutUs: 'About Us',
    ourServices: 'Our Services',
    blog: 'Blog',
    refundPolicy: 'Refund Policy',
    newsletterTitle: 'Stay Updated',
    newsletterDesc: 'Subscribe to our newsletter to get the latest logistics news and updates.',
    subscribe: 'Subscribe',
    addressLabel: 'Cairo, Egypt - Public Free Zone',
    paymentMethods: 'Payment Methods',
    // Shipping Forms Specific
    cityIn: 'City In / Issued At',
    freightPayableAt: 'Freight Payable At',
    numberOfOriginalBl: 'No. of Original B/L',
    numberOfCopyBl: 'No. of Copy B/L',
    netWeightKgs: 'Net Weight (KGS)',
    grossWeightKgs: 'Gross Weight (KGS)',
    footerSignature: 'Footer / Signature',
    vesselNameForm: 'Vessel Name',
    // New Home
    brandName: 'Logistics B Arab',
    knowledgeBridgeTag: 'Knowledge Bridge • Business • Bilingual',
    heroTitle_new: 'Your Hub for Maritime Logistics',
    heroSubtitle_new: 'An integrated ecosystem combining knowledge, tools, and trusted partners for logistics professionals in the Arab world, powered by the latest AI technologies.',
    heroCardTitle: 'Integrated Maritime Intelligence',
    heroCardSubtitle: 'Unifying AI advisories, workflow automation, and human expertise for every shipment decision.',
    heroCardRoute: 'Jeddah → Rotterdam',
    heroCardRouteDesc: 'Red Sea Alerts • Recommended Route via Cape of Good Hope',
    heroCardHs: 'HS 8418.69 — Cooling Units',
    heroCardHsDesc: 'Simplified fees for Saudi Arabia and UAE • Checklist ready',
    logisticsHubTitle: 'Logistics Services Center',
    heroCta1: 'Discover Tools',
    heroCta2: 'Browse Directory',
    alertRouteLabel: 'Live Route Alert',
    alertCustomsLabel: 'Customs Glance',
    dashboardLive: 'LIVE',
    dashboardAnalysis: 'Gemini Analysis',
    dashboardStats: 'System Activity',
    stat1: 'Optimized Routes',
    stat2: 'Partner Companies',
    stat3: 'Knowledge Articles',
    stat4: 'Verified Experts',
    poweredByAI: 'Powered by Gemini AI',
    howItWorksTitle: 'How Logistics B Arab Works',
    howItWorksSubtitle: 'We combine automation and field expertise to ensure your business runs smoothly with full compliance and proactive decision-making.',
    howItWorks1Title: 'Record & Operate Shipments',
    howItWorks1Desc: 'Automate documents, start shipments, and monitor every stage with full visibility shared with your team.',
    howItWorks2Title: 'Find Partners',
    howItWorks2Desc: 'Search our trusted directory for shipping lines, brokers, and the most experienced freight forwarders in the region.',
    howItWorks3Title: 'Discover Tools',
    howItWorks3Desc: 'Benefit from smart modules designed specifically for maritime operations in the MENA region.',
    poweredByGemini: 'Powered by Gemini AI',
    toolsTitle: 'Integrated Tools for Operations',
    toolsSubtitle: 'Each tool connects to live data from the knowledge base and trade directory to give you fast, fact-based decisions.',
    tools1Desc: 'Virtual advisor analyzing geopolitical events to suggest optimal sea routes with confidence scores.',
    tools2Desc: 'Understands goods descriptions in Arabic/English, even with typos, to display the optimal HS code instantly.',
    tools3Desc: 'Generates standard commercial documents compliant with standards, with smart calculation and logo/stamp addition in PDF format.',
    tools4Desc: 'Unified platform for freight forwarders to track every stop, update stakeholders, and maintain full visibility.',
    communityInsights: 'Community Insights',
    communityInsightsDesc: 'What industry leaders are saying about Logistics B Arab.',
    latestArticles: 'Latest Articles',
    viewAllArticles: 'View Knowledge Base',
    testimonial1: "The bilingual HS code search tool saved our documentation process. Perfectly tailored to the challenges we face daily.",
    testimonial1_author: "Import & Export Specialist",
    testimonial1_role: "Retail Sector",
    testimonial2: "Logistics B Arab became our regional intelligence layer. Insights and partner alignment helped us cut delays by half.",
    testimonial2_author: "Logistics Manager",
    testimonial2_role: "Major Export Company",
    ctaTitle: 'Modernize Your Logistics Today',
    ctaSubtitle: 'Join thousands of professionals optimizing their supply chain with Logistics B Arab.',
    startNow: 'Get Started Free',
    specialThanksTitle: 'Strategic Partner Spotlight',
    specialThanksDesc: 'Acknowledging IGL for their industry expertise and commitment to digital transformation in logistics.',
    viewPartner: 'View Profile',
    // Footer
    footerSubtitle_new: 'Your primary platform for logistics information and smart tools in the Arab world.',
    footerLinksExplore: 'Resources',
    subscribeToUpdates: 'Contact Us',
    subscribeToUpdatesDesc_new: 'Get the latest maritime news and platform updates.',
    enterYourEmail: 'Enter your email',
    subscribe_new: 'Subscribe',
    footerRights: 'All rights reserved',
    english: 'English',
    arabic: 'العربية',
    // Route Planner
    origin: 'Origin',
    destination: 'Destination',
    goodsDescription: 'Goods Description',
    getAdvice: 'Analyze Route',
    shippingAdvice: 'AI Analysis & Advice',
    shipmentType: 'Shipment Type',
    quantityWeightVolume: 'Quantity / Weight / Volume',
    fcl: 'Full Container Load (FCL)',
    lcl: 'Less than Container Load (LCL)',
    saveAdvice: 'Save Analysis',
    adviceSaved: 'Analysis Saved!',
    savedAdvice: 'Saved Analyses',
    noSavedAdvice: 'No saved analyses found.',
    viewAdvice: 'View Details',
    deleteAdvice: 'Delete',
    groundingSources: 'Verified Sources (Google Maps)',
    saveRoute: 'Save Route',
    loadRoute: 'Load',
    savedRoutes: 'Saved Routes',
    routeName: 'Route Name',
    noSavedRoutes: 'No saved routes found.',
    enterRouteName: 'Name this route',
    routeSaved: 'Route saved!',
    pickupDate: 'Pickup Date',
    expectedDepartureDate: 'Expected Departure Date',
    // HS Code Finder
    productDescription: 'Describe product (e.g., "frozen shrimp", "cotton shirts")',
    findHSCode: 'Identify Code',
    hsCodeSuggestions: 'Suggested Codes',
    recentSearches: 'Recent History',
    // Knowledge Base
    knowledgeBaseHeroTitle: 'Logistics Knowledge Hub',
    knowledgeBaseHeroSubtitle: 'Insights, regulations, and guides for the modern logistician.',
    searchArticles: 'Search knowledge base...',
    logisticsDictionary: 'Logistics Dictionary',
    dictionaryDesc: 'Common maritime and shipping terms defined.',
    lawsAndRegulations: 'Laws & Regulations',
    lawsDesc: 'Updated customs and trade laws for the Arab region.',
    // Article Categories
    'sea-freight': 'Sea Freight',
    'customs': 'Customs',
    'ports': 'Ports',
    'news': 'News',
    'logistics-tech': 'Tech',
    'warehousing': 'Warehousing',
    'global-trade': 'Global Trade',
    'financial': 'Finance',
    'educational': 'Education',
    'laws-and-regulations': 'Regulations',
    // Directory
    addCompany: 'List Your Company',
    searchByName: 'Search companies, ports, services...',
    searchByPort: 'Filter by port...',
    allCategories: 'All Categories',
    selectCompanyType: 'Select Company Type',
    companyName: 'Company Name',
    companyNameAr: 'Company Name (Arabic)',
    companyNameEn: 'Company Name (English)',
    companyWebsite: 'Website',
    verificationDocument: 'Commercial Register / Tax Card',
    uploadVerification: 'Upload Verification Document (PDF/Image)',
    companyAddedSuccess: 'Application submitted successfully! We will verify your details.',
    companyDescription: 'Company Description',
    contactInfo: 'Contact',
    phone: 'Phone',
    address: 'Address',
    category: 'Category',
    sortBy: 'Sort By',
    sortName: 'Name',
    sortCategory: 'Category',
    commercialRegistration: 'Registration Document',
    uploadFile: 'Upload',
    fileTooLarge: 'File size exceeds 5MB limit.',
    branchDetails: 'Branches',
    workingHours: 'Hours',
    peakTimes: 'Crowd Levels',
    peakTimeSlot1: '8-10am',
    peakTimeSlot2: '10-12pm',
    peakTimeSlot3: '12-2pm',
    peakTimeSlot4: '2-4pm',
    peakTimeSlot5: '4-6pm',
    busynessLevel: 'Activity: {level}/5',
    importantServiceAreas: 'Key Routes',
    featuredAreas: 'Specialized Services',
    generateEmail: 'Draft Email',
    contactCompany: 'Contact Company',
    emailSubject: 'Inquiry regarding logistics services',
    emailBody: 'Dear Team,\n\nI am interested in your services. Please contact me back.\n\nBest regards,',
    companySubmitted: 'Submission Received',
    companySubmittedDesc: 'Your company has been added to the directory.',
    loginToView: 'Login to view',
    'shipping-line': 'Shipping Line',
    'freight-forwarder': 'Freight Forwarder',
    'transportation': 'Transporter',
    'customs-broker': 'Customs Broker',
    myFavorites: 'Favorites',
    addToFavorites: 'Save',
    removeFromFavorites: 'Unsave',
    noFavorites: 'No favorites yet.',
    rateThisCompany: 'Rate',
    yourRating: 'Your Rating',
    averageRating: 'Rating',
    noRatingsYet: 'No ratings',
    ratingsCount: '({count})',
    reviews: 'Reviews',
    writeReview: 'Write a Review',
    ratingCommentPlaceholder: 'Share your experience with this company...',
    submitReview: 'Post Review',
    resetFilters: 'Reset Filters',
    verified: 'Verified',
    visitWebsite: 'Visit Website',
    callNow: 'Call Now',
    directoryStats: 'Partner Ecosystem',
    totalCompanies: 'Companies Listed',
    requestQuote: 'Request Quote',
    sendRequest: 'Send Request',
    quoteDetails: 'Quote Details',
    cargoType: 'Cargo Type',
    preferredDate: 'Preferred Date',
    additionalNotes: 'Additional Notes',
    requestSentSuccess: 'Request sent successfully!',
    companyAbout: 'About Us',
    services: 'Services',
    operatingPorts: 'Operating Ports',
    mainBranch: 'Main Branch',
    // Auth & Profile
    login: 'Login',
    logout: 'Sign Out',
    signup: 'Sign Up',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    alreadyHaveAccount: 'Have an account?',
    dontHaveAccount: "New here?",
    createAccount: 'Create Account',
    premiumFeature: 'Premium',
    unlockAllFeatures: 'Upgrade to unlock full potential.',
    subscribeNow: 'Subscribe',
    name: 'Name',
    loginWelcome: 'Welcome Back',
    loginSubtext: 'Access your dashboard.',
    registerWelcome: 'Get Started',
    registerSubtext: 'Join the network.',
    profileTitle: 'Account',
    subscriptionStatus: 'Plan',
    currentPlan: 'Current',
    yourCurrentPlan: 'Your Plan',
    expiresOn: 'Renews',
    upgradeSubscription: 'Upgrade',
    manageSubscription: 'Manage',
    notSubscribed: 'Free Tier',
    chooseAPlan: 'Select a plan',
    subscribedTo: 'Subscribed to {planName}',
    activityOverview: 'Activity Overview',
    operationsToday: 'Operations Today',
    operationsMonth: 'Operations This Month',
    totalShipments: 'Total Shipments',
    activeShipments: 'Active Shipments',
    completedShipments: 'Completed',
    estimatedProfit: 'Est. Profit',
    savedRoutesCount: 'Saved Routes',
    totalRevenue: 'Total Revenue',
    viewDashboard: 'Dashboard',
    myShipments: 'My Shipments',
    accountSettings: 'Account Settings',
    // Auth - New
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    enterEmailToReset: 'Enter your email to receive reset instructions.',
    resetEmailSent: 'Password reset email sent!',
    sendResetLink: 'Send Reset Link',
    rememberMe: 'Remember me',
    loginWithGoogle: 'Login with Google',
    or: 'Or',
    // Contact Us
    contactFormTitle: 'Get in Touch',
    contactFormSubtitle: 'We are here to help with any inquiries.',
    yourName: 'Name',
    yourEmail: 'Email',
    message: 'Message',
    sendMessage: 'Send',
    messageSent: 'Sent!',
    messageSentDesc: 'We will reply shortly.',
    emailSupportTitle: 'Email',
    emailAddress: 'support@logisticsbarab.com',
    phoneSupportTitle: 'Phone',
    phoneNumber: '+20 123 456 7890',
    // Invoice Generator
    invoiceAndPackingList: 'Trade Docs Generator',
    invoiceAndPackingListSubtitle: 'Generate standardized Commercial Invoices and Packing Lists.',
    logoAndSeal: 'Branding',
    companyLogo: 'Logo',
    logoPlaceholder: 'Upload Logo',
    companySeal: 'Seal/Signature',
    sealPlaceholder: 'Upload Seal',
    exporterDetails: 'Exporter',
    exporterName: 'Exporter Name',
    exporterAddress: 'Exporter Address',
    importerDetails: 'Importer',
    importerName: 'Importer Name',
    importerAddress: 'Importer Address',
    invoiceAndShipmentDetails: 'Shipment Data',
    invoiceNo: 'Invoice #',
    invoiceDate: 'Date',
    packingIn: 'Packing',
    pol: 'P.O.L',
    pod: 'P.O.D',
    incoterm: 'Incoterm',
    bankDetails: 'Banking Info',
    advisingBank: 'Advising Bank',
    bankName: 'Bank Name',
    accountName: 'Account Name',
    swiftCode: 'Swift Code',
    iban: 'IBAN',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    updateItem: 'Update',
    itemDescription: 'Description',
    packagesCount: 'Pkg Count',
    packageUnit: 'Unit',
    netWtPerUnit: 'Net/Unit',
    totalNetWt: 'Total Net',
    grossWtPerUnit: 'Gross/Unit',
    totalGrossWt: 'Total Gross',
    pricePerKgs: 'Price/Unit',
    delete: 'Delete',
    edit: 'Edit',
    // Shipping Forms
    selectForm: 'Select Document Type',
    billOfLading: 'Bill of Lading',
    commercialInvoice: 'Commercial Invoice',
    shipperExporter: 'Shipper',
    consignee: 'Consignee',
    notifyParty: 'Notify',
    vesselVoyage: 'Vessel / Voyage',
    portOfLoading: 'Port of Loading',
    portOfDischarge: 'Port of Discharge',
    placeOfReceipt: 'Receipt Place',
    placeOfDelivery: 'Delivery Place',
    marksAndNumbers: 'Marks & Nos',
    noOfContainers: 'No. Containers',
    kindOfPackages: 'Pkg Kind',
    descriptionOfGoods: 'Goods Description',
    grossWeight: 'Gross Wt (KGS)',
    measurement: 'Measure (CBM)',
    // Shipping Forms - Preview
    shippingDeclaration: 'Shipping Declaration',
    finalShippingDeclaration: 'Final Shipping Declaration',
    cityInDate: 'Issued At/Date',
    shipperNameAddress: 'Shipper Details',
    consigneeNameAddress: 'Consignee Details',
    notifyNameAddress: 'Notify Details',
    blOriginalCopy: 'B/L Counts',
    netWeight: 'Net Wt',
    signatureAndStamp: 'Signature',
    // Shipment Tracker
    addShipment: 'New Shipment',
    trackShipment: 'Track',
    shipmentId: 'Ref / B/L No.',
    status: 'Status',
    customer: 'Customer',
    driver: 'Driver',
    vehicle: 'Truck/Vehicle',
    progress: 'Progress',
    eta: 'ETA',
    updates: 'Log',
    nextCheckpoint: 'Next Step',
    pending: 'Pending',
    assigned: 'Assigned',
    in_transit: 'In Transit',
    delivered: 'Delivered',
    pickup_order_issued: 'Pickup Order',
    driver_assigned_for_pickup: 'Driver for Pickup',
    container_picked_up: 'Container Picked',
    at_shipper_for_loading: 'At Loading',
    loading_complete_enroute_to_port: 'En Route to Port',
    documents_submitted: 'Docs Submitted',
    customs_clearance_export: 'Export Customs',
    customs_clearance_import: 'Import Customs',
    ready_for_delivery: 'Ready for Del.',
    noShipments: 'No active shipments.',
    shipmentDetails: 'Details',
    backToDashboard: 'Dashboard',
    assignDriverAndVehicle: 'Assign Transport',
    startShipment: 'Start Voyage',
    updateLocation: 'Location',
    markAsDelivered: 'Complete Delivery',
    driverId: 'Driver ID',
    vehicleId: 'Vehicle ID',
    assign: 'Assign',
    currentLocation: 'Location',
    update: 'Update',
    confirmDelivery: 'Confirm delivery completion?',
    confirm: 'Confirm',
    shipmentWeight: 'Weight',
    shipmentValue: 'Value',
    shipmentTimeline: 'Timeline',
    shipmentAdded: 'Created',
    driverAssigned: 'Driver Assigned',
    shipmentStarted: 'Started',
    arrivedAt: 'Arrived',
    shipmentDelivered: 'Delivered',
    issuePickupOrder: 'Issue Pickup',
    assignDriverForPickup: 'Assign Pickup',
    confirmContainerPickup: 'Confirm Pickup',
    confirmArrivalAtShipper: 'Confirm Arrival',
    markLoadingComplete: 'Loading Done',
    containerId: 'Container #',
    pickupOrderIssued: 'Pickup Issued',
    driverAssignedForPickup: 'Pickup Driver Assigned',
    containerPickedUp: 'Container Picked',
    arrivedAtShipper: 'Arrived at Shipper',
    loadingComplete: 'Loading Complete',
    oceanTransitStarted: 'Transit Started',
    preTransitDetails: 'Pre-Transit',
    setEta: 'Set ETA',
    estimatedArrivalTime: 'ETA',
    delayAlert: 'Delay',
    noDelay: 'On Time',
    shipmentDelayed: 'Delayed',
    vesselAndVoyage: 'Vessel Info',
    vesselName: 'Vessel',
    voyageNumber: 'Voyage',
    keyDates: 'Schedule',
    estimatedDeparture: 'ETD',
    actualDeparture: 'ATD',
    actualArrival: 'ATA',
    documents: 'Docs',
    noDocuments: 'No docs.',
    uploadDocument: 'Upload',
    documentName: 'Name',
    documentType: 'Type',
    temperatureControlled: 'Reefer',
    temperatureSetting: 'Temp (°C)',
    reeferMonitoring: 'Monitoring',
    submitDocuments: 'Submit Docs',
    startExportClearance: 'Export Clear.',
    logVesselDeparture: 'Log Departure',
    startImportClearance: 'Import Clear.',
    markReadyForDelivery: 'Ready for Del.',
    logDepartureTime: 'Log ATD',
    logArrivalTime: 'Log ATA',
    documentsSubmitted: 'Docs Submitted',
    exportClearanceStarted: 'Exp. Clearance',
    vesselDeparted: 'Vessel Departed',
    importClearanceStarted: 'Imp. Clearance',
    shipmentReadyForDelivery: 'Cleared & Ready',
    shipmentInfo: 'Shipment',
    logisticsInfo: 'Logistics',
    driverAndVehicleInfo: 'Transport',
    shippingLine: 'Line',
    bookingNo: 'Booking #',
    containerSize: 'Size',
    sealNo: 'Seal #',
    driverName: 'Driver',
    driverPhone: 'Phone',
    truckPlate: 'Truck',
    trailerPlate: 'Trailer',
    addShipmentUpdate: 'Add Note',
    enterUpdateMessage: 'Message...',
    addUpdate: 'Add',
    customsBroker: 'Customs Broker',
    customsBrokerName: 'Customs Broker Name',
    transportCompany: 'Transport Company',
    importFromChat: 'Import from Chat',
    pasteChatHere: 'Paste logistics chat log here (WhatsApp, etc.)...',
    parseChat: 'Parse Data',
    analyzing: 'Analyzing...',
    shipmentsFound: 'Shipments Found',
    import: 'Import',
    saveAll: 'Save All',
    // New keys
    loadDataFromShipment: 'Load from Shipment',
    loadFromShipment: 'Load',
    shipmentNotFound: 'ID "{shipmentId}" not found.',
    dataLoadedSuccess: 'Loaded {shipmentId}',
    previewInEnglish: 'Preview EN',
    previewInArabic: 'Preview AR',
    switchedToPreview: 'Preview: {lang}',
    financeInfo: 'Financials',
    cost: 'Purchase Price',
    price: 'Sale Price',
    profit: 'Profit',
    editShipment: 'Edit',
    saveChanges: 'Save',
    certType: 'Certificate',
    certificateOfOrigin: 'Cert. of Origin',
    phytosanitaryCertificate: 'Phytosanitary',
    leagueOfArabStates: 'Arab League',
    parties: 'Parties',
    exporterNameAddressCountry: '1. Exporter',
    importerNameAddressCountry: '2. Importer',
    producerAndAddress: 'Producer',
    certNo: 'Cert #',
    portOfShipmentOptional: 'Port of Shipment',
    vessel: 'Vessel',
    blNo: 'B/L No.',
    from: 'From',
    to: 'To',
    date: 'Date',
    commercialInvoiceNoAndDate: 'Inv No & Date',
    countryOfOrigin: 'Origin',
    countryOfDestination: 'Destination',
    goodsAndMeasures: 'Goods',
    number: '#',
    numCategoriesOfParcels: 'Pkgs',
    grossMassKg: 'Gross (kg)',
    statementByExporter: 'Exporter Statement',
    certifyGoodsOfOrigin: 'Certification',
    agriCertPlaceholder: 'Coming soon.',
    officialPreview: 'Preview',
    enterDocumentData: 'Input Data',
    phytoNo: 'No.',
    phytoTo: '1. To',
    phytoExporter: '2. Exporter',
    phytoConsignee: '3. Consignee',
    phytoConveyance: '4. Conveyance',
    phytoEntryPoint: '5. Entry Point',
    phytoPlaceOfOrigin: '6. Origin',
    phytoDistinguishingMarks: '7. Marks',
    phytoNumAndDesc: '8. Number/Desc',
    phytoNameOfProduce: '9. Produce Name',
    phytoBotanicalName: '10. Botanical',
    phytoCertificationText: '11. Cert Text',
    phytoTreatment: '12. Treatment',
    phytoChemical: '13. Chemical',
    phytoConcentration: '14. Conc.',
    phytoDurationTemp: '15. Dur/Temp',
    phytoAddInfo: '16. Info',
    phytoAddDeclaration: '17. Declaration',
    phytoInspectionDate: '18. Insp. Date',
    phytoIssueDate: '19. Issue Date',
    phytoIssuePlace: '20. Issue Place',
    phytoInspectorName: '21. Inspector',
    phytoAuthOfficerName: '22. Officer',
    phytoPortOfLoading: '23. P.O.L',
    phytoStamp: '24. Stamp',
    phytoSignature: '25. Signature',
    routePlannerDesc: 'AI-optimized sea routes.',
    hsCodeFinderDesc: 'Instant code classification.',
    invoiceGeneratorDesc: 'Professional trade docs.',
    shippingFormsDesc: 'Create Shipping Declarations (SD) and Final Shipping Declarations (FSD) with automated templates.',
    shipmentTrackerDesc: 'Live milestone tracking.',
    documentEditorDesc: 'Official certificates.',
    pricingSubtitle: 'Flexible plans for growing businesses.',
    monthlyPlan: 'Monthly',
    yearlyPlan: 'Yearly',
    monthlyPrice: '250',
    yearlyPrice: '2400',
    currency: 'EGP',
    perMonth: '/mo',
    perYear: '/yr',
    savePrice: 'Save',
    billedMonthly: 'Billed monthly',
    billedYearly: 'Billed yearly',
    planFeatures: 'Includes:',
    feature1: 'AI Route Planner',
    feature2: 'HS Code Finder',
    feature3: 'Doc Generators',
    feature4: 'Shipment Tracker',
    feature5: 'Directory Access',
    mostPopular: 'Best Value',
    tariffItem: 'Tariff Item',
    originCriterion: 'Origin Criterion',
    remarks: 'Remarks',
    cumulationApplied: 'Cumulation applied',
    issuedRetrospectively: 'ISSUED RETROSPECTIVELY',
    duplicate: 'DUPLICATE',
    transportDetails: 'Transport Details',
    previewSettings: 'Preview & Print Settings',
    fontSize: 'Font Size (pt)',
    pageWidth: 'Page Width (mm)',
    pageHeight: 'Page Height (mm)',
    resetSettings: 'Reset Default',
    requiredField: 'This field is required',
    invalidEmail: 'Invalid email address',
    atLeastOnePort: 'Please enter at least one port',
    searchShipmentsPlaceholder: 'Search Ref, Exporter, Broker, Ports...',
    filterByDate: 'Filter by Date',
    allDates: 'All Time',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    // Document Formatting
    formatting: 'Formatting',
    fontSizeLabel: 'Font Size',
    alignmentLabel: 'Alignment',
    increaseFont: 'Increase Font',
    decreaseFont: 'Decrease Font',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    // Knowledge and Directory
    knowledgeSectionTitle: 'Knowledge Base',
    knowledgeSectionDesc: 'A continually updated information engine covering port news, customs regulations, and modern technologies with a focus on the Arab region.',
    directorySectionTitle: 'Company Directory',
    directorySectionDesc: 'Search a selected list of shipping lines, freight forwarders, brokers, and certified customs brokers.',
    knowledgeCard1Title: 'Port Monitoring',
    knowledgeCard1Desc: 'Daily alerts on congestion, closures, and weather conditions in major Middle East ports.',
    knowledgeCard2Title: 'Compliance Guides',
    knowledgeCard2Desc: 'Detailed procedures for customs compliance in the Gulf, Levant, and North Africa backed by official references.',
    knowledgeCard3Title: 'Tech & Innovation',
    knowledgeCard3Desc: 'Analyses on AI adoption, visibility platforms, and digital transformation solutions for the maritime sector.',
    directoryCard1Title: 'Shipping Lines',
    directoryCard1Desc: 'Container, Ro-Ro, and bulk vessels serving major Arab ports.',
    directoryCard2Title: 'Freight Forwarders',
    directoryCard2Desc: 'Comprehensive partners with local expertise and value-added services for the shipping journey.',
    directoryCard3Title: 'Brokers & Agents',
    directoryCard3Desc: 'Specialists in vessel chartering, documentation, and maritime agency services.',
    // Profile - Sidebar & Settings
    notifications: 'Notifications',
    helpAndSupport: 'Help & Support',
    security: 'Security',
    notificationsSettings: 'Notification Preferences',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    appUpdates: 'App Updates',
    faqs: 'Frequently Asked Questions',
    contactSupport: 'Contact Support',
    receiveEmails: 'Receive emails about shipment updates',
    receiveSms: 'Receive SMS for critical alerts',
    receiveAppUpdates: 'Receive news about new features',
    privacyPolicy: 'Privacy Policy',
    termsAndConditions: 'Terms & Conditions',
    commonQuestions: 'Common questions about shipping, tracking, and payments.',
    reachSupportTeam: 'Reach out to our support team via email or phone.',
    legalInformation: 'Legal information and user agreements.',
    dataProtection: 'Data protection and privacy policies.',
    // New Customs Expense Terms
    operationNumber: 'Operation No.',
    certificateNumber: 'Certificate No.',
    agriculturalInspection: 'Agricultural Inspection',
    foodSafety: 'Food Safety Authority',
    nathria: 'Petty Expenses (Nathria)',
    mashal: 'Porterage/Handling (Mashal)',
    officialReceipts: 'Official Receipts',
    clearanceFees: 'Clearance Fees',
    doorInspection: 'Door Inspection',
    expensesBreakdown: 'Expenses Breakdown',
    printMode: 'Print Mode',
    fullDocument: 'Full Document',
    dataOnly: 'Data Only',
    margins: 'Page Margins',
    marginTop: 'Top Margin',
    marginLeft: 'Left Margin',
    baseFontSize: 'Base Font Size',
    uploadPhoto: 'Upload Photo',
    companyDetails: 'Company Details',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    profileUpdated: 'Profile updated successfully!',
    // Keys for Sidebar & Author Info
    youMightLike: 'You Might Also Like',
    weeklyLogisticsBrief: 'Weekly Logistics Brief',
    getMarketUpdates: 'Get the latest market updates delivered to your inbox.',
    editorialTeam: 'Logistics B Arab Editorial',
    marketIntelligence: 'Market Intelligence Team',
  },
  ar: {
    loading: 'جار التحميل...',
    close: 'إغلاق',
    submit: 'إرسال',
    save: 'حفظ',
    share: 'مشاركة',
    printOrSave: 'طباعة / PDF',
    downloadPdf: 'تحميل PDF',
    readMore: 'المزيد',
    showLess: 'عرض أقل',
    viewDetails: 'التفاصيل',
    back: 'رجوع',
    cancel: 'إلغاء',
    talkWithUs: 'تحدث معنا',
    actions: 'إجراءات',
    saveDraft: 'حفظ مسودة',
    loadDraft: 'تحميل مسودة',
    clearForm: 'مسح',
    draftSaved: 'تم الحفظ!',
    draftLoaded: 'تم التحميل!',
    formCleared: 'تم المسح!',
    confirmLoad: 'تحميل المسودة المحفوظة؟ سيتم استبدال البيانات الحالية.',
    confirmClear: 'مسح النموذج؟ ستفقد البيانات.',
    foundSavedDraft: 'يوجد مسودة محفوظة. تحميلها؟',
    confirmDeleteDocument: 'هل أنت متأكد أنك تريد حذف "{docName}"؟',
    confirmDeleteItem: 'هل أنت متأكد أنك تريد حذف هذا الصنف؟',
    confirmDeleteShipment: 'هل أنت متأكد أنك تريد حذف الشحنة {id}؟',
    confirmDeleteRoute: 'هل أنت متأكد أنك تريد حذف هذا المسار؟',
    confirmDeleteUser: 'هل أنت متأكد أنك تريد حذف المستخدم {email}؟',
    confirmDeleteArticle: 'هل أنت متأكد أنك تريد حذف هذا المقال؟',
    confirmDeleteCompany: 'هل أنت متأكد أنك تريد حذف شركة {name}؟',
    home: 'الرئيسية',
    articles: 'المقالات',
    tools: 'الأدوات',
    knowledgeBase: 'المعرفة',
    directory: 'الدليل',
    routePlanner: 'مخطط المسارات',
    hsCodeFinder: 'كود HS',
    invoiceGenerator: 'الفاتورة وبيان العبوة',
    shippingForms: 'نماذج SD/FSD',
    shipmentTracker: 'شحناتك',
    documentEditor: 'الشهادات',
    contactUs: 'اتصل بنا',
    profile: 'حسابي',
    pricing: 'الباقات',
    privacy: 'سياسة الخصوصية',
    terms: 'الشروط والأحكام',
    faq: 'الأسئلة الشائعة',
    // Footer Specific - Arabic
    quickLinks: 'روابط سريعة',
    supportLegal: 'الدعم والقانونية',
    aboutUs: 'من نحن',
    ourServices: 'خدماتنا',
    blog: 'المدونة',
    refundPolicy: 'سياسة الاسترجاع',
    newsletterTitle: 'ابقَ على اطلاع',
    newsletterDesc: 'اشترك في قائمتنا البريدية للحصول على آخر أخبار اللوجستيات.',
    subscribe: 'اشتراك',
    addressLabel: 'القاهرة، مصر - المنطقة الحرة العامة',
    paymentMethods: 'طرق الدفع',
    brandName: 'Logistics B Arab',
    knowledgeBridgeTag: 'جسر المعرفة • الأعمال • ثنائي اللغة',
    heroTitle_new: 'مركزك لخدمات اللوجستيات البحرية',
    heroSubtitle_new: 'منظومة متكاملة تجمع المعرفة، والأدوات، والشركاء الموثوقين لمهنيي اللوجستيات في العالم العربي، مدعومة بأحدث تقنيات الذكاء الاصطناعي.',
    heroCardTitle: 'Integrated Maritime Intelligence',
    heroCardSubtitle: 'Unifying AI advisories, workflow automation, and human expertise for every shipment decision.',
    heroCardRoute: 'جدة ← روتردام',
    heroCardRouteDesc: 'تنبيهات البحر الأحمر مفعلة • المسار الموصى به عبر رأس الرجاء الصالح',
    heroCardHs: 'HS 8418.69 — وحدات تبريد',
    heroCardHsDesc: 'رسوم مبسطة للسعودية والإمارات • قائمة تحقق جاهزة',
    logisticsHubTitle: 'مركز الخدمات اللوجستية',
    heroCta1: 'اكتشف الأدوات',
    heroCta2: 'تصفح الدليل',
    alertRouteLabel: 'تنبيه مسار مباشر',
    alertCustomsLabel: 'لمحة جمركية',
    dashboardLive: 'مباشر',
    dashboardAnalysis: 'تحليل Gemini',
    dashboardStats: 'نشاط النظام',
    stat1: 'مسارات محسنة',
    stat2: 'شركات شريكة',
    stat3: 'مقالات معرفية',
    stat4: 'خبراء موثقون',
    poweredByAI: 'مدعوم من Gemini AI',
    howItWorksTitle: 'كيف تعمل منصة Logistics B Arab',
    howItWorksSubtitle: 'نمزج بين الأتمتة والخبرة الميدانية لنضمن سير أعمالك بانسيابية وامتثال كامل واستباقية في اتخاذ القرار.',
    howItWorks1Title: 'سجل وشغّل الشحنات',
    howItWorks1Desc: 'أتمت المستندات، وابدأ الشحنات، وراقب كل مرحلة برؤية كاملة ومشتركة مع فرقك.',
    howItWorks2Title: 'اعثر على الشركاء',
    howItWorks2Desc: 'ابحث في دليلنا الموثوق عن خطوط الشحن، الوسطاء، ووكلاء الشحن الأكثر خبرة في المنطقة.',
    howItWorks3Title: 'اكتشاف الأدوات',
    howItWorks3Desc: 'استفد من وحدات ذكية مصممة خصيصاً للعمليات البحرية في منطقة الشرق الأوسط وشمال أفريقيا.',
    poweredByGemini: 'مدعوم من Gemini AI',
    toolsTitle: 'أدوات متكاملة لإدارة عملياتك اللوجستية',
    toolsSubtitle: 'كل أداة ترتبط ببيانات حية من قاعدة المعرفة والدليل التجاري لتمنحك قرارات سريعة ومبنية على حقائق.',
    tools1Desc: 'مستشار افتراضي يحلل الأحداث الجيوسياسية ويقترح أفضل المسارات البحرية مع نسب ثقة واضحة.',
    tools2Desc: 'يستوعب أوصاف البضائع بالعربية أو الإنجليزية، حتى مع الأخطاء الإملائية، ليعرض الرمز الجمركي الأمثل فورًا.',
    tools3Desc: 'ينشئ مستندات تجارية متوافقة مع المعايير مع احتساب ذكي وإضافة الشعار والختم بصيغة PDF جاهزة للتصدير.',
    tools4Desc: 'منصة موحدة لوكلاء الشحن لمتابعة كل محطة، وتحديث الأطراف المعنية، والحفاظ على رؤية كاملة لسير الشحنة.',
    communityInsights: 'آراء المجتمع',
    communityInsightsDesc: '',
    latestArticles: 'أحدث المقالات',
    viewAllArticles: 'عرض قاعدة المعرفة',
    testimonial1: "أداة البحث عن رموز HS ثنائية اللغة أنقذت عملية التوثيق. مفصلة تمامًا للتحديات التي نواجهها يوميًا.",
    testimonial1_author: "أخصائي استيراد وتصدير",
    testimonial1_role: "قطاع التجزئة",
    testimonial2: "أصبحت Logistics B Arab طبقة الذكاء الإقليمي لدينا. ساعدتنا الرؤى ومواءمة الشركاء على خفض التأخيرات إلى النصف.",
    testimonial2_author: "مدير لوجستي",
    testimonial2_role: "شركة تصدير كبرى",
    ctaTitle: 'طوّر أعمالك اللوجستية اليوم',
    ctaSubtitle: 'انضم لآلاف المحترفين الذين يحسنون سلاسل إمدادهم مع لوجستيكس ب عرب.',
    startNow: 'ابدأ مجاناً',
    specialThanksTitle: 'شريك استراتيجي',
    specialThanksDesc: 'تقدير خاص للمجموعة الدولية للوجستيات (IGL) لخبرتهم الصناعية ودعمهم للتحول الرقمي.',
    viewPartner: 'ملف الشريك',
    footerSubtitle_new: 'منصتك الأولى للمعلومات اللوجستية والأدوات الذكية في العالم العربي.',
    footerLinksExplore: 'المنصة',
    subscribeToUpdates: 'تواصل معنا',
    subscribeToUpdatesDesc_new: 'احصل على آخر أخبار الملاحة وتحديثات المنصة في بريدك.',
    enterYourEmail: 'بريدك الإلكتروني',
    subscribe_new: 'اشتراك',
    footerRights: 'جميع الحقوق محفوظة',
    english: 'English',
    arabic: 'العربية',
    origin: 'المصدر',
    destination: 'الوجهة',
    goodsDescription: 'وصف البضائع',
    getAdvice: 'تحليل المسار',
    shippingAdvice: 'تحليل ونصائح AI',
    shipmentType: 'نوع الشحنة',
    quantityWeightVolume: 'الكمية / الوزن',
    fcl: 'حاوية كاملة (FCL)',
    lcl: 'جزء من حاوية (LCL)',
    saveAdvice: 'حفظ التحليل',
    adviceSaved: 'تم الحفظ!',
    savedAdvice: 'التحليلات المحفوظة',
    noSavedAdvice: 'لا توجد تحليلات.',
    viewAdvice: 'عرض التفاصيل',
    deleteAdvice: 'حذف',
    groundingSources: 'مصادر موثقة (خرائط جوجل)',
    saveRoute: 'حفظ المسار',
    loadRoute: 'تحميل',
    savedRoutes: 'المسارات المحفوظة',
    routeName: 'اسم المسار',
    noSavedRoutes: 'لا توجد مسارات.',
    enterRouteName: 'اسم المسار',
    routeSaved: 'تم الحفظ!',
    pickupDate: 'تاريخ التحميل',
    expectedDepartureDate: 'تاريخ السفر المتوقع',
    productDescription: 'وصف المنتج (مثال: "جمبري مجمد"، "قمصان قطن")',
    findHSCode: 'تحديد الكود',
    hsCodeSuggestions: 'الأكواد المقترحة',
    recentSearches: 'السجل',
    knowledgeBaseHeroTitle: 'قاعدة المعرفة',
    knowledgeBaseHeroSubtitle: 'محرك معلومات متجدد يغطي أخبار الموانئ، واللوائح الجمركية، والتقنيات الحديثة مع تركيز على المنطقة العربية.',
    searchArticles: 'بحث في المعرفة...',
    logisticsDictionary: 'القاموس اللوجستي',
    dictionaryDesc: 'تعريفات المصطلحات البحرية والشحن الشائعة.',
    lawsAndRegulations: 'القوانين واللوائح',
    lawsDesc: 'أحدث قوانين الجمارك والتجارة للمنطقة العربية.',
    'sea-freight': 'شحن بحري',
    'customs': 'جمارك',
    'ports': 'رصد الموانئ',
    'news': 'أخبار',
    'logistics-tech': 'التقنية والابتكار',
    'warehousing': 'تخزين',
    'global-trade': 'تجارة دولية',
    'financial': 'مالية',
    'educational': 'تعليمي',
    'laws-and-regulations': 'أدلة الامتثال',
    addCompany: 'أضف شركتك',
    searchByName: 'ابحث عن شركات، موانئ، خدمات...',
    searchByPort: 'تصفية بالميناء...',
    allCategories: 'الكل',
    selectCompanyType: 'اختر نوع الشركة',
    companyName: 'اسم الشركة',
    companyNameAr: 'الاسم (عربي)',
    companyNameEn: 'الاسم (إنجليزي)',
    companyWebsite: 'الموقع الإلكتروني',
    verificationDocument: 'السجل التجاري / البطاقة الضريبية',
    uploadVerification: 'رفع المستند (PDF/صورة)',
    companyAddedSuccess: 'تم إرسال طلب إضافة الشركة للمراجعة بنجاح!',
    companyDescription: 'نبذة عن الشركة',
    contactInfo: 'تواصل',
    phone: 'هاتف',
    address: 'عنوان',
    category: 'التصنيف',
    sortBy: 'ترتيب حسب',
    sortName: 'الاسم',
    sortCategory: 'التصنيف',
    commercialRegistration: 'السجل التجاري',
    uploadFile: 'رفع',
    fileTooLarge: 'حجم الملف يتجاوز ٥ ميجابايت.',
    branchDetails: 'الفروع',
    workingHours: 'الدوام',
    peakTimes: 'الازدحام',
    peakTimeSlot1: '٨-١٠ص',
    peakTimeSlot2: '١٠-١٢ظ',
    peakTimeSlot3: '١٢-٢ظ',
    peakTimeSlot4: '٢-٤م',
    peakTimeSlot5: '٤-٦م',
    busynessLevel: 'النشاط: {level}/5',
    importantServiceAreas: 'أهم المسارات',
    featuredAreas: 'خدمات مميزة',
    generateEmail: 'صياغة إيميل',
    contactCompany: 'تواصل مع الشركة',
    emailSubject: 'استفسار بخصوص خدمات لوجستية',
    emailBody: 'السادة فريق العمل،\n\nأنا مهتم بخدماتكم وأرغب في التواصل.\n\nمع أطيب التحيات،',
    companySubmitted: 'تم الإرسال',
    companySubmittedDesc: 'تمت إضافة شركتك إلى الدليل.',
    loginToView: 'سجل للمشاهدة',
    'shipping-line': 'خطوط الشحن',
    'freight-forwarder': 'وكلاء الشحن',
    'transportation': 'نقل بري',
    'customs-broker': 'الوسطاء والوكلاء',
    myFavorites: 'المفضلة',
    addToFavorites: 'حفظ',
    removeFromFavorites: 'إلغاء الحفظ',
    noFavorites: 'لا مفضلة.',
    rateThisCompany: 'قيّم',
    yourRating: 'تقييمك',
    averageRating: 'التقييم',
    noRatingsYet: 'لا تقييمات',
    ratingsCount: '({count})',
    reviews: 'المراجعات',
    writeReview: 'أكتب مراجعة',
    ratingCommentPlaceholder: 'شارك تجربتك مع هذه الشركة...',
    submitReview: 'نشر',
    resetFilters: 'إعادة تعيين',
    verified: 'موثق',
    visitWebsite: 'زيارة الموقع',
    callNow: 'اتصال',
    directoryStats: 'منظومة الشركاء',
    totalCompanies: 'شركة مدرجة',
    requestQuote: 'طلب عرض سعر',
    sendRequest: 'إرسال الطلب',
    quoteDetails: 'تفاصيل الطلب',
    cargoType: 'نوع البضاعة',
    preferredDate: 'الموعد المفضل',
    additionalNotes: 'ملاحظات إضافية',
    requestSentSuccess: 'تم إرسال طلبك بنجاح!',
    companyAbout: 'عن الشركة',
    services: 'الخدمات',
    operatingPorts: 'موانئ التشغيل',
    mainBranch: 'الفرع الرئيسي',
    login: 'دخول',
    logout: 'خروج',
    signup: 'تسجيل',
    register: 'حساب جديد',
    email: 'البريد',
    password: 'كلمة المرور',
    alreadyHaveAccount: 'لديك حساب؟',
    dontHaveAccount: 'جديد هنا؟',
    createAccount: 'إنشاء حساب',
    premiumFeature: 'مميز',
    unlockAllFeatures: 'رقِ حسابك لفتح كافة المزايا.',
    subscribeNow: 'اشترك',
    name: 'الاسم',
    loginWelcome: 'أهلاً بعودتك',
    loginSubtext: 'ادخل للوحة التحكم.',
    registerWelcome: 'ابدأ معنا',
    registerSubtext: 'انضم للشبكة.',
    profileTitle: 'الحساب',
    subscriptionStatus: 'الباقة',
    currentPlan: 'الحالية',
    yourCurrentPlan: 'باقتك',
    expiresOn: 'تجدد في',
    upgradeSubscription: 'ترقية',
    manageSubscription: 'إدارة',
    notSubscribed: 'مجانية',
    chooseAPlan: 'اختر باقة',
    subscribedTo: 'مشترك في {planName}',
    activityOverview: 'نظرة عامة',
    operationsToday: 'عمليات اليوم',
    operationsMonth: 'عمليات الشهر',
    totalShipments: 'إجمالي الشحنات',
    activeShipments: 'الشحنات النشطة',
    completedShipments: 'مكتملة',
    estimatedProfit: 'الربح المقدر',
    savedRoutesCount: 'مسارات محفوظة',
    totalRevenue: 'إجمالي الإيراد',
    viewDashboard: 'لوحة التحكم',
    myShipments: 'شحناتي',
    accountSettings: 'إعدادات الحساب',
    // Auth - New
    forgotPassword: 'نسيت كلمة المرور؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    enterEmailToReset: 'أدخل بريدك الإلكتروني لاستلام تعليمات إعادة التعيين.',
    resetEmailSent: 'تم إرسال بريد إعادة التعيين.',
    sendResetLink: 'إرسال الرابط',
    rememberMe: 'تذكرني',
    loginWithGoogle: 'تسجيل الدخول بواسطة جوجل',
    or: 'أو',
    // Contact Us
    contactFormTitle: 'تواصل معنا',
    contactFormSubtitle: 'نحن هنا للمساعدة.',
    yourName: 'الاسم',
    yourEmail: 'البريد',
    message: 'الرسالة',
    sendMessage: 'إرسال',
    messageSent: 'تم!',
    messageSentDesc: 'سنرد قريباً.',
    emailSupportTitle: 'بريد',
    emailAddress: 'support@logisticsbarab.com',
    phoneSupportTitle: 'هاتف',
    phoneNumber: '+٢٠ ١٢٣ ٤٥٦ ٧٨٩٠',
    invoiceAndPackingList: 'مولد الفواتير وقوائم التعبئة',
    invoiceAndPackingListSubtitle: 'ينشئ مستندات تجارية متوافقة مع المعايير مع احتساب ذكي وإضافة الشعار والختم بصيغة PDF جاهزة للتصدير.',
    logoAndSeal: 'الهوية',
    companyLogo: 'شعار',
    logoPlaceholder: 'رفع الشعار',
    companySeal: 'ختم/توقيع',
    sealPlaceholder: 'رفع الختم',
    exporterDetails: 'المصدر',
    exporterName: 'اسم المصدر',
    exporterAddress: 'عنوان المصدر',
    importerDetails: 'المستورد',
    importerName: 'اسم المستورد',
    importerAddress: 'عنوان المستورد',
    invoiceAndShipmentDetails: 'بيانات الشحنة',
    invoiceNo: 'رقم الفاتورة',
    invoiceDate: 'التاريخ',
    packingIn: 'تعبئة',
    pol: 'ميناء الشحن',
    pod: 'ميناء الوصول',
    incoterm: 'Incoterm',
    bankDetails: 'البنك',
    advisingBank: 'النبك المبلغ',
    bankName: 'اسم البنك',
    accountName: 'اسم الحساب',
    swiftCode: 'Swift',
    iban: 'IBAN',
    addItem: 'إضافة',
    editItem: 'تعديل',
    updateItem: 'تحديث',
    itemDescription: 'الوصف',
    packagesCount: 'العدد',
    packageUnit: 'الوحدة',
    netWtPerUnit: 'صافي/وحدة',
    totalNetWt: 'إجمالي صافي',
    grossWtPerUnit: 'قائم/وحدة',
    totalGrossWt: 'إجمالي قائم',
    pricePerKgs: 'سعر/وحدة',
    delete: 'حذف',
    edit: 'تعديل',
    selectForm: 'اختر المستند',
    billOfLading: 'بوليصة شحن',
    commercialInvoice: 'فاتورة تجارية',
    shipperExporter: 'الشاحن',
    consignee: 'المرسل إليه',
    notifyParty: 'الطرف المُخطر',
    vesselVoyage: 'سفينة / رحلة',
    portOfLoading: 'ميناء الشحن',
    portOfDischarge: 'ميناء الوصول',
    placeOfReceipt: 'استلام',
    placeOfDelivery: 'تسليم',
    marksAndNumbers: 'علامات وأرقام',
    noOfContainers: 'عدد الحاويات',
    kindOfPackages: 'نوع الطرود',
    descriptionOfGoods: 'وصف البضاعة',
    grossWeight: 'وزن قائم (كجم)',
    measurement: 'قياس (م³)',
    shippingDeclaration: 'إقرار شحن',
    finalShippingDeclaration: 'إقرار نهائي',
    cityInDate: 'صدر في/بتاريخ',
    shipperNameAddress: 'الشاحن',
    consigneeNameAddress: 'المرسل إليه',
    notifyNameAddress: 'المُخطر',
    blOriginalCopy: 'نسخ البوليصة',
    netWeight: 'الصافي',
    signatureAndStamp: 'توقيع',
    addShipment: 'شحنة جديدة',
    trackShipment: 'متتبع الشحنات',
    shipmentId: 'رقم مرجعي/بوليصة',
    status: 'الحالة',
    customer: 'العميل',
    driver: 'السائق',
    vehicle: 'شاحنة',
    progress: 'التقدم',
    eta: 'الوصول',
    updates: 'سجل',
    nextCheckpoint: 'التالي',
    pending: 'انتظار',
    assigned: 'تعيين',
    in_transit: 'في الطريق',
    delivered: 'تم التوصيل',
    pickup_order_issued: 'أمر شحن',
    driver_assigned_for_pickup: 'سائق للسحب',
    container_picked_up: 'سحب الحاوية',
    at_shipper_for_loading: 'عند العميل',
    loading_complete_enroute_to_port: 'نحو الميناء',
    documents_submitted: 'تقديم المستندات',
    customs_clearance_export: 'جمرك صادر',
    customs_clearance_import: 'جمرك وارد',
    ready_for_delivery: 'جاهزة للتسليم',
    noShipments: 'لا شحنات نشطة.',
    shipmentDetails: 'تفاصيل',
    backToDashboard: 'اللوحة',
    assignDriverAndVehicle: 'تعيين نقل',
    startShipment: 'بدء الرحلة',
    updateLocation: 'موقع',
    markAsDelivered: 'إتمام التوصيل',
    driverId: 'م. السائق',
    vehicleId: 'م. المركبة',
    assign: 'تعيين',
    currentLocation: 'موقع',
    update: 'تحديث',
    confirmDelivery: 'تأكيد التوصيل؟',
    confirm: 'تأكيد',
    shipmentWeight: 'وزن',
    shipmentValue: 'قيمة',
    shipmentTimeline: 'الجدول',
    shipmentAdded: 'تم الإنشاء',
    driverAssigned: 'تعيين سائق',
    shipmentStarted: 'بدأت',
    arrivedAt: 'وصلت',
    shipmentDelivered: 'تمت',
    issuePickupOrder: 'إصدار أمر',
    assignDriverForPickup: 'تعيين سحب',
    confirmContainerPickup: 'تأكيد السحب',
    confirmArrivalAtShipper: 'تأكيد الوصول',
    markLoadingComplete: 'انتهاء التحميل',
    containerId: 'حاوية #',
    pickupOrderIssued: 'أمر صادر',
    driverAssignedForPickup: 'سائق معين',
    containerPickedUp: 'سُحبت',
    arrivedAtShipper: 'عند العميل',
    loadingComplete: 'تحميل مكتمل',
    oceanTransitStarted: 'بدء إبحار',
    preTransitDetails: 'ما قبل النقل',
    setEta: 'تحديد ETA',
    estimatedArrivalTime: 'ETA',
    delayAlert: 'تأخير',
    noDelay: 'في الموعد',
    shipmentDelayed: 'متأخرة',
    vesselAndVoyage: 'السفينة',
    vesselName: 'السفينة',
    voyageNumber: 'الرحلة',
    keyDates: 'المواعيد',
    estimatedDeparture: 'ETD',
    actualDeparture: 'ATD',
    actualArrival: 'ATA',
    documents: 'مستندات',
    noDocuments: 'لا يوجد.',
    uploadDocument: 'رفع',
    documentName: 'الاسم',
    documentType: 'النوع',
    temperatureControlled: 'مبردة',
    temperatureSetting: 'حرارة (°م)',
    reeferMonitoring: 'مراقبة',
    submitDocuments: 'تقديم',
    startExportClearance: 'تخليص صادر',
    logVesselDeparture: 'تسجيل مغادرة',
    startImportClearance: 'تخليص وارد',
    markReadyForDelivery: 'جاهزة للتسليم',
    logDepartureTime: 'سجل ATD',
    logArrivalTime: 'سجل ATA',
    documentsSubmitted: 'تم التقديم',
    exportClearanceStarted: 'بدأ التخليص',
    vesselDeparted: 'غادرت',
    importClearanceStarted: 'بدأ التخليص',
    shipmentReadyForDelivery: 'جاهزة',
    shipmentInfo: 'الشحنة',
    logisticsInfo: 'لوجستيات',
    driverAndVehicleInfo: 'نقل',
    shippingLine: 'الخط',
    bookingNo: 'حجز #',
    containerSize: 'حجم',
    sealNo: 'سيل #',
    driverName: 'سائق',
    driverPhone: 'هاتف',
    truckPlate: 'شاحنة',
    trailerPlate: 'مقطورة',
    addShipmentUpdate: 'ملاحظة',
    enterUpdateMessage: 'رسالة...',
    addUpdate: 'إضافة',
    customsBroker: 'المخلص الجمركي',
    customsBrokerName: 'مستخلص جمركي',
    transportCompany: 'شركة النقل',
    importFromChat: 'استيراد من المحادثة',
    pasteChatHere: 'الصق نص المحادثة اللوجستية هنا (واتساب، إلخ)...',
    parseChat: 'تحليل البيانات',
    analyzing: 'جارٍ التحليل...',
    shipmentsFound: 'شحنات تم العثور عليها',
    import: 'استيراد',
    saveAll: 'حفظ الكل',
    loadDataFromShipment: 'تحميل من شحنة',
    loadFromShipment: 'تحميل',
    shipmentNotFound: 'الرقم "{shipmentId}" غير موجود.',
    dataLoadedSuccess: 'تم التحميل {shipmentId}',
    previewInEnglish: 'معاينة EN',
    previewInArabic: 'معاينة AR',
    switchedToPreview: 'معاينة: {lang}',
    financeInfo: 'مالية',
    cost: 'سعر الشراء',
    price: 'سعر البيع',
    profit: 'ربح',
    editShipment: 'تعديل',
    saveChanges: 'حفظ',
    certType: 'نوع الشهادة',
    certificateOfOrigin: 'منشأ',
    phytosanitaryCertificate: 'صحة نباتية',
    leagueOfArabStates: 'جامعة الدول',
    parties: 'أطراف',
    exporterNameAddressCountry: '١. المصدر',
    importerNameAddressCountry: '٢. المستورد',
    producerAndAddress: 'المنتج',
    certNo: 'شهادة #',
    portOfShipmentOptional: 'ميناء الشحن',
    vessel: 'سفينة',
    blNo: 'بوليصة #',
    from: 'من',
    to: 'إلى',
    date: 'التاريخ',
    commercialInvoiceNoAndDate: 'فاتورة #',
    countryOfOrigin: 'منشأ',
    countryOfDestination: 'وجهة',
    goodsAndMeasures: 'بضائع',
    number: '#',
    numCategoriesOfParcels: 'طرود',
    grossMassKg: 'قائم (كجم)',
    statementByExporter: 'إقرار',
    certifyGoodsOfOrigin: 'تصديق',
    agriCertPlaceholder: 'قريباً.',
    officialPreview: 'معاينة',
    enterDocumentData: 'إدخال',
    phytoNo: 'رقم',
    phytoTo: '١. إلى',
    phytoExporter: '٢. المصدر',
    phytoConsignee: '٣. المستلم',
    phytoConveyance: '٤. نقل',
    phytoEntryPoint: '٥. دخول',
    phytoPlaceOfOrigin: '٦. منشأ',
    phytoDistinguishingMarks: '٧. علامات',
    phytoNumAndDesc: '٨. وصف',
    phytoNameOfProduce: '٩. منتج',
    phytoBotanicalName: '١٠. نباتي',
    phytoCertificationText: '١١. نص',
    phytoTreatment: '١٢. معاملة',
    phytoChemical: '١٣. كيميائي',
    phytoConcentration: '١٤. تركيز',
    phytoDurationTemp: '١٥. مدة/حرارة',
    phytoAddInfo: '١٦. معلومات',
    phytoAddDeclaration: '١٧. إقرار',
    phytoInspectionDate: '١٨. فحص',
    phytoIssueDate: '١٩. إصدار',
    phytoIssuePlace: '٢٠. مكان',
    phytoInspectorName: '٢١. مفتش',
    phytoAuthOfficerName: '٢٢. مسؤول',
    phytoPortOfLoading: '٢٣. تحميل',
    phytoStamp: '٢٤. ختم',
    phytoSignature: '٢٥. توقيع',
    routePlannerDesc: 'مستشار افتراضي يحلل الأحداث الجيوسياسية ويقترح أفضل المسارات البحرية مع نسب ثقة واضحة.',
    hsCodeFinderDesc: 'يستوعب أوصاف البضائع بالعربية أو الإنجليزية، حتى مع الأخطاء الإملائية، ليعرض الرمز الجمركي الأمثل فورًا.',
    invoiceGeneratorDesc: 'ينشئ مستندات تجارية متوافقة مع المعايير مع احتساب ذكي وإضافة الشعار والختم بصيغة PDF جاهزة للتصدير.',
    shippingFormsDesc: 'إصدار إقرارات الشحن (SD) والإقرارات النهائية (FSD) بشكل فوري ومعتمد.',
    shipmentTrackerDesc: 'منصة موحدة لوكلاء الشحن لمتابعة كل محطة، وتحديث الأطراف المعنية، والحفاظ على رؤية كاملة لسير الشحنة.',
    documentEditorDesc: 'شهادات رسمية.',
    pricingSubtitle: 'خطط مرنة للأعمال النامية.',
    monthlyPlan: 'شهرية',
    yearlyPlan: 'سنوية',
    monthlyPrice: '٢٥٠',
    yearlyPrice: '٢٤٠٠',
    currency: 'ج.م',
    perMonth: '/شهر',
    perYear: '/سنة',
    savePrice: 'وفر',
    billedMonthly: 'تدفع شهرياً',
    billedYearly: 'تدفع سنوياً',
    planFeatures: 'تشمل:',
    feature1: 'تخطيط مسارات',
    feature2: 'أكواد جمركية',
    feature3: 'مستندات',
    feature4: 'تتبع شحنات',
    feature5: 'دليل شركات',
    mostPopular: 'قيمة أفضل',
    tariffItem: 'بند جمركي',
    originCriterion: 'معيار المنشأ',
    remarks: 'ملاحظات',
    cumulationApplied: 'تراكم المنشأ',
    issuedRetrospectively: 'صدر بأثر رجعي',
    duplicate: 'نسخة طبق الأصل',
    transportDetails: 'تفاصيل النقل',
    previewSettings: 'إعدادات المعاينة والطباعة',
    fontSize: 'حجم الخط (pt)',
    pageWidth: 'عرض الصفحة (مم)',
    pageHeight: 'ارتفاع الصفحة (مم)',
    resetSettings: 'إعادة ضبط',
    requiredField: 'هذا الحقل مطلوب',
    invalidEmail: 'البريد الإلكتروني غير صالح',
    atLeastOnePort: 'يرجى إدخال ميناء واحد على الأقل',
    searchShipmentsPlaceholder: 'بحث بالمرجع، المصدر، المخلص، الموانئ...',
    filterByDate: 'تصفية بالتاريخ',
    allDates: 'كل الأوقات',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    // Document Formatting
    formatting: 'تنسيق',
    fontSizeLabel: 'حجم الخط',
    alignmentLabel: 'محاذاة',
    increaseFont: 'تكبير الخط',
    decreaseFont: 'تصغير الخط',
    alignLeft: 'محاذاة لليسار',
    alignCenter: 'محاذاة للوسط',
    alignRight: 'محاذاة لليمين',
    // Knowledge and Directory
    knowledgeSectionTitle: 'قاعدة المعرفة',
    knowledgeSectionDesc: 'محرك معلومات متجدد يغطي أخبار الموانئ، واللوائح الجمركية، والتقنيات الحديثة مع تركيز على المنطقة العربية.',
    directorySectionTitle: 'دليل الشركات',
    directorySectionDesc: 'ابحث في قائمة مختارة من خطوط الشحن، ووكلاء الشحن، والوسطاء، والمخلصين الجمركيين المعتمدين.',
    knowledgeCard1Title: 'رصد الموانئ',
    knowledgeCard1Desc: 'تنبيهات يومية عن الازدحام، الإغلاقات، والأحوال الجوية في الموانئ الرئيسية بمنطقة الشرق الأوسط.',
    knowledgeCard2Title: 'أدلة الامتثال',
    knowledgeCard2Desc: 'إجراءات تفصيلية للامتثال الجمركي في الخليج والمشرق وشمال أفريقيا مدعومة بالمراجع الرسمية.',
    knowledgeCard3Title: 'التقنية والابتكار',
    knowledgeCard3Desc: 'تحليلات حول تبني الذكاء الاصطناعي، ومنصات الرؤية، وحلول التحول الرقمي لقطاع النقل البحري.',
    directoryCard1Title: 'خطوط الشحن',
    directoryCard1Desc: 'سفن حاويات ودحرجة وبضائع سائبة تخدم أهم الموانئ العربية.',
    directoryCard2Title: 'وكلاء الشحن',
    directoryCard2Desc: 'شركاء شاملون يمتلكون خبرة محلية وخدمات قيمة مضافة لرحلة الشحن.',
    directoryCard3Title: 'الوسطاء والوكلاء',
    directoryCard3Desc: 'متخصصون في تأجير السفن، المستندات، وخدمات الوكالات البحرية.',
    // Shipping Forms Specific
    cityIn: 'المدينة / صدر في',
    freightPayableAt: 'مكان دفع النولون',
    numberOfOriginalBl: 'عدد النسخ الأصلية',
    numberOfCopyBl: 'عدد النسخ المصورة',
    netWeightKgs: 'الوزن الصافي (كجم)',
    grossWeightKgs: 'الوزن القائم (كجم)',
    footerSignature: 'التذييل / التوقيع',
    vesselNameForm: 'اسم السفينة',
    // Profile - Sidebar & Settings
    notifications: 'الإشعارات',
    helpAndSupport: 'المساعدة والدعم',
    security: 'الأمان',
    notificationsSettings: 'تفضيلات الإشعارات',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    smsNotifications: 'رسائل نصية SMS',
    appUpdates: 'تحديثات التطبيق',
    faqs: 'الأسئلة الشائعة',
    contactSupport: 'اتصل بالدعم',
    receiveEmails: 'استلام رسائل بريد حول تحديثات الشحنات',
    receiveSms: 'استلام رسائل نصية للتنبيهات الهامة',
    receiveAppUpdates: 'استلام أخبار حول المميزات الجديدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsAndConditions: 'الشروط والأحكام',
    commonQuestions: 'أسئلة شائعة حول الشحن والتتبع والدفع.',
    reachSupportTeam: 'تواصل مع فريق الدعم عبر البريد أو الهاتف.',
    legalInformation: 'المعلومات القانونية واتفاقيات الاستخدام.',
    dataProtection: 'حماية البيانات وسياسات الخصوصية.',
    // New Customs Expense Terms ARABIC
    operationNumber: 'رقم العملية',
    certificateNumber: 'رقم الشهادة',
    agriculturalInspection: 'فحص زراعي',
    foodSafety: 'هيئة سلامة الغذاء',
    nathria: 'نثرية',
    mashal: 'مشال',
    officialReceipts: 'إيصالات رسمية',
    clearanceFees: 'أتعاب تخليص',
    doorInspection: 'فحص على الباب',
    expensesBreakdown: 'بيان المصروفات',
    printMode: 'وضع الطباعة',
    fullDocument: 'مستند كامل',
    dataOnly: 'البيانات فقط',
    margins: 'هوامش الصفحة',
    marginTop: 'الهامش العلوي',
    marginLeft: 'الهامش الأيسر',
    baseFontSize: 'حجم الخط الأساسي',
    uploadPhoto: 'رفع صورة',
    companyDetails: 'تفاصيل الشركة',
    securitySettings: 'إعدادات الأمان',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    // Keys for Sidebar & Author Info
    youMightLike: 'قد يعجبك أيضاً',
    weeklyLogisticsBrief: 'ملخص اللوجستيات الأسبوعي',
    getMarketUpdates: 'احصل على آخر تحديثات السوق مباشرة في بريدك الوارد.',
    editorialTeam: 'فريق تحرير لوجستيكس ب عرب',
    marketIntelligence: 'فريق استخبارات السوق',
  },
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const [theme, setTheme] = useState<Theme>('light');

  useEffect(() => {
    const persistedTheme = window.localStorage.getItem('theme') as Theme | null;
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    
    if (persistedTheme) {
      setTheme(persistedTheme);
    } else {
      setTheme(systemPrefersDark ? 'dark' : 'light');
    }
  }, []);

  useEffect(() => {
      document.documentElement.setAttribute('data-theme', theme);
      if (theme === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
      window.localStorage.setItem('theme', theme);
  }, [theme]);


  const dir = useMemo(() => (language === 'ar' ? 'rtl' : 'ltr'), [language]);
  
  document.documentElement.lang = language;
  document.documentElement.dir = dir;

  const t = useCallback((key: string, replacements: Record<string, string> = {}): string => {
    let translation = (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
    Object.keys(replacements).forEach(placeholder => {
        translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
    });
    return translation;
  }, [language]);

  const value: LocalizationContextType = {
    language,
    setLanguage,
    t,
    dir,
    theme,
    setTheme,
  };

  return React.createElement(
    LocalizationContext.Provider,
    { value: value },
    children
  );
};

export const useLocalization = (): LocalizationContextType => {
  const context = useContext(LocalizationContext);
  if (context === undefined) {
    throw new Error('useLocalization must be used within an AppProvider');
  }
  return context;
};
