
import React, { createContext, useState, useContext, useMemo, useCallback, useEffect } from 'react';
import type { Language } from './types';

// Define theme type
export type Theme = 'light' | 'dark';

// Define the shape of the localization context
interface LocalizationContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
  dir: 'ltr' | 'rtl';
  theme: Theme;
  setTheme: (theme: Theme) => void;
}

// Translations object
const translations = {
  en: {
    // General
    loading: 'Loading...',
    close: 'Close',
    submit: 'Submit',
    save: 'Save',
    share: 'Share',
    printOrSave: 'Print / Download PDF',
    downloadPdf: 'Download PDF',
    readMore: 'Read More',
    showLess: 'Show Less',
    viewDetails: 'View Details',
    back: 'Back',
    cancel: 'Cancel',
    talkWithUs: 'Talk with Us',
    actions: 'Actions',
    saveDraft: 'Save Draft',
    loadDraft: 'Load Draft',
    clearForm: 'Clear Form',
    draftSaved: 'Draft saved successfully!',
    draftLoaded: 'Draft loaded successfully!',
    formCleared: 'Form cleared!',
    confirmLoad: 'Are you sure you want to load the saved draft? This will overwrite any unsaved changes.',
    confirmClear: 'Are you sure you want to clear the form? All entered data will be lost.',
    foundSavedDraft: 'We found a saved draft. Would you like to load it?',
    confirmDeleteDocument: 'Are you sure you want to delete "{docName}"?',
    confirmDeleteItem: 'Are you sure you want to delete this item?',
    confirmDeleteShipment: 'Are you sure you want to delete shipment {id}?',
    confirmDeleteRoute: 'Are you sure you want to delete this route?',
    confirmDeleteUser: 'Are you sure you want to delete user {email}?',
    confirmDeleteArticle: 'Are you sure you want to delete this article?',
    confirmDeleteCompany: 'Are you sure you want to delete company {name}?',
    // App sections
    home: 'Home',
    articles: 'Articles',
    tools: 'Tools',
    knowledgeBase: 'Knowledge Base',
    directory: 'Directory',
    routePlanner: 'Route Planner',
    hsCodeFinder: 'HS Code Finder',
    invoiceGenerator: 'Invoice & Packing List',
    shippingForms: 'SD/FSD',
    shipmentTracker: 'Your Shipments',
    documentEditor: 'Certificates',
    contactUs: 'Contact Us',
    profile: 'Profile',
    pricing: 'Pricing',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    faq: 'FAQ',
    // Footer Specific
    quickLinks: 'Quick Links',
    supportLegal: 'Support & Legal',
    aboutUs: 'About Us',
    ourServices: 'Our Services',
    blog: 'Blog',
    refundPolicy: 'Refund Policy',
    newsletterTitle: 'Stay Updated',
    newsletterDesc: 'Subscribe to our newsletter to get the latest logistics news and updates.',
    subscribe: 'Subscribe',
    addressLabel: 'Cairo, Egypt - Public Free Zone',
    paymentMethods: 'Payment Methods',
    // Shipping Forms Specific
    cityIn: 'City In / Issued At',
    freightPayableAt: 'Freight Payable At',
    numberOfOriginalBl: 'No. of Original B/L',
    numberOfCopyBl: 'No. of Copy B/L',
    netWeightKgs: 'Net Weight (KGS)',
    grossWeightKgs: 'Gross Weight (KGS)',
    footerSignature: 'Footer / Signature',
    vesselNameForm: 'Vessel Name',
    // New Home
    brandName: 'Logistics B Arabc',
    knowledgeBridgeTag: 'Knowledge Bridge • Business • Bilingual',
    heroTitle_new: 'Your Hub for Maritime Logistics',
    heroSubtitle_new: 'An integrated ecosystem combining knowledge, tools, and trusted partners for logistics professionals in the Arab world, powered by the latest AI technologies.',
    heroCardTitle: 'Integrated Maritime Intelligence',
    heroCardSubtitle: 'Unifying AI advisories, workflow automation, and human expertise for every shipment decision.',
    heroCardRoute: 'Jeddah → Rotterdam',
    heroCardRouteDesc: 'Red Sea Alerts • Recommended Route via Cape of Good Hope',
    heroCardHs: 'HS 8418.69 — Cooling Units',
    heroCardHsDesc: 'Simplified fees for Saudi Arabia and UAE • Checklist ready',
    logisticsHubTitle: 'Logistics Services Center',
    heroCta1: 'Discover Tools',
    heroCta2: 'Browse Directory',
    alertRouteLabel: 'Live Route Alert',
    alertCustomsLabel: 'Customs Glance',
    dashboardLive: 'LIVE',
    dashboardAnalysis: 'Gemini Analysis',
    dashboardStats: 'System Activity',
    stat1: 'Optimized Routes',
    stat2: 'Partner Companies',
    stat3: 'Knowledge Articles',
    stat4: 'Verified Experts',
    poweredByAI: 'Powered by Gemini AI',
    howItWorksTitle: 'How Logistics B Arabc Works',
    howItWorksSubtitle: 'We combine automation and field expertise to ensure your business runs smoothly with full compliance and proactive decision-making.',
    howItWorks1Title: 'Record & Operate Shipments',
    howItWorks1Desc: 'Automate documents, start shipments, and monitor every stage with full visibility shared with your team.',
    howItWorks2Title: 'Find Partners',
    howItWorks2Desc: 'Search our trusted directory for shipping lines, brokers, and the most experienced freight forwarders in the region.',
    howItWorks3Title: 'Discover Tools',
    howItWorks3Desc: 'Benefit from smart modules designed specifically for maritime operations in the MENA region.',
    poweredByGemini: 'Powered by Gemini AI',
    toolsTitle: 'Integrated Tools for Operations',
    toolsSubtitle: 'Each tool connects to live data from the knowledge base and trade directory to give you fast, fact-based decisions.',
    tools1Desc: 'Virtual advisor analyzing geopolitical events to suggest optimal sea routes with confidence scores.',
    tools2Desc: 'Understands goods descriptions in Arabic/English, even with typos, to display the optimal HS code instantly.',
    tools3Desc: 'Generates standard commercial documents compliant with standards, with smart calculation and logo/stamp addition in PDF format.',
    tools4Desc: 'Unified platform for freight forwarders to track every stop, update stakeholders, and maintain full visibility.',
    communityInsights: 'Community Insights',
    communityInsightsDesc: 'What industry leaders are saying about Logistics B Arabc.',
    latestArticles: 'Latest Articles',
    viewAllArticles: 'View Knowledge Base',
    testimonial1: "The bilingual HS code search tool saved our documentation process. Perfectly tailored to the challenges we face daily.",
    testimonial1_author: "Import & Export Specialist",
    testimonial1_role: "Retail Sector",
    testimonial2: "Logistics B Arabc became our regional intelligence layer. Insights and partner alignment helped us cut delays by half.",
    testimonial2_author: "Logistics Manager",
    testimonial2_role: "Major Export Company",
    ctaTitle: 'Modernize Your Logistics Today',
    ctaSubtitle: 'Join thousands of professionals optimizing their supply chain with Logistics B Arabc.',
    startNow: 'Get Started Free',
    specialThanksTitle: 'Strategic Partner Spotlight',
    specialThanksDesc: 'Acknowledging IGL for their industry expertise and commitment to digital transformation in logistics.',
    viewPartner: 'View Profile',
    // Footer
    footerSubtitle_new: 'Your primary platform for logistics information and smart tools in the Arab world.',
    footerLinksExplore: 'Resources',
    subscribeToUpdates: 'Contact Us',
    subscribeToUpdatesDesc_new: 'Get the latest maritime news and platform updates.',
    enterYourEmail: 'Enter your email',
    subscribe_new: 'Subscribe',
    footerRights: 'All rights reserved',
    english: 'English',
    arabic: 'العربية',
    // Route Planner
    origin: 'Origin',
    destination: 'Destination',
    goodsDescription: 'Goods Description',
    getAdvice: 'Analyze Route',
    shippingAdvice: 'AI Analysis & Advice',
    shipmentType: 'Shipment Type',
    quantityWeightVolume: 'Quantity / Weight / Volume',
    fcl: 'Full Container Load (FCL)',
    lcl: 'Less than Container Load (LCL)',
    saveAdvice: 'Save Analysis',
    adviceSaved: 'Analysis Saved!',
    savedAdvice: 'Saved Analyses',
    noSavedAdvice: 'No saved analyses found.',
    viewAdvice: 'View Details',
    deleteAdvice: 'Delete',
    groundingSources: 'Verified Sources (Google Maps)',
    saveRoute: 'Save Route',
    loadRoute: 'Load',
    savedRoutes: 'Saved Routes',
    routeName: 'Route Name',
    noSavedRoutes: 'No saved routes found.',
    enterRouteName: 'Name this route',
    routeSaved: 'Route saved!',
    pickupDate: 'Pickup Date',
    expectedDepartureDate: 'Expected Departure Date',
    // HS Code Finder
    productDescription: 'Describe product (e.g., "frozen shrimp", "cotton shirts")',
    findHSCode: 'Identify Code',
    hsCodeSuggestions: 'Suggested Codes',
    recentSearches: 'Recent History',
    // Knowledge Base
    knowledgeBaseHeroTitle: 'Logistics Knowledge Hub',
    knowledgeBaseHeroSubtitle: 'Insights, regulations, and guides for the modern logistician.',
    searchArticles: 'Search knowledge base...',
    logisticsDictionary: 'Logistics Dictionary',
    dictionaryDesc: 'Common maritime and shipping terms defined.',
    lawsAndRegulations: 'Laws & Regulations',
    lawsDesc: 'Updated customs and trade laws for the Arab region.',
    // Article Categories
    'sea-freight': 'Sea Freight',
    'customs': 'Customs',
    'ports': 'Ports',
    'news': 'News',
    'logistics-tech': 'Tech',
    'warehousing': 'Warehousing',
    'global-trade': 'Global Trade',
    'financial': 'Finance',
    'educational': 'Education',
    'laws-and-regulations': 'Regulations',
    // Directory
    addCompany: 'List Your Company',
    searchByName: 'Search companies, ports, services...',
    searchByPort: 'Filter by port...',
    allCategories: 'All Categories',
    selectCompanyType: 'Select Company Type',
    companyName: 'Company Name',
    companyNameAr: 'Company Name (Arabic)',
    companyNameEn: 'Company Name (English)',
    companyWebsite: 'Website',
    verificationDocument: 'Commercial Register / Tax Card',
    uploadVerification: 'Upload Verification Document (PDF/Image)',
    companyAddedSuccess: 'Application submitted successfully! We will verify your details.',
    companyDescription: 'Company Description',
    contactInfo: 'Contact',
    phone: 'Phone',
    address: 'Address',
    category: 'Category',
    sortBy: 'Sort By',
    sortName: 'Name',
    sortCategory: 'Category',
    commercialRegistration: 'Registration Document',
    uploadFile: 'Upload',
    fileTooLarge: 'File size exceeds 5MB limit.',
    branchDetails: 'Branches',
    workingHours: 'Hours',
    peakTimes: 'Crowd Levels',
    peakTimeSlot1: '8-10am',
    peakTimeSlot2: '10-12pm',
    peakTimeSlot3: '12-2pm',
    peakTimeSlot4: '2-4pm',
    peakTimeSlot5: '4-6pm',
    busynessLevel: 'Activity: {level}/5',
    importantServiceAreas: 'Key Routes',
    featuredAreas: 'Specialized Services',
    generateEmail: 'Draft Email',
    contactCompany: 'Contact Company',
    emailSubject: 'Inquiry regarding logistics services',
    emailBody: 'Dear Team,\n\nI am interested in your services. Please contact me back.\n\nBest regards,',
    companySubmitted: 'Submission Received',
    companySubmittedDesc: 'Your company has been added to the directory.',
    loginToView: 'Login to view',
    'shipping-line': 'Shipping Line',
    'freight-forwarder': 'Freight Forwarder',
    'transportation': 'Transporter',
    'customs-broker': 'Customs Broker',
    myFavorites: 'Favorites',
    addToFavorites: 'Save',
    removeFromFavorites: 'Unsave',
    noFavorites: 'No favorites yet.',
    rateThisCompany: 'Rate',
    yourRating: 'Your Rating',
    averageRating: 'Rating',
    noRatingsYet: 'No ratings',
    ratingsCount: '({count})',
    reviews: 'Reviews',
    writeReview: 'Write a Review',
    ratingCommentPlaceholder: 'Share your experience with this company...',
    submitReview: 'Post Review',
    resetFilters: 'Reset Filters',
    verified: 'Verified',
    visitWebsite: 'Visit Website',
    callNow: 'Call Now',
    directoryStats: 'Partner Ecosystem',
    totalCompanies: 'Companies Listed',
    requestQuote: 'Request Quote',
    sendRequest: 'Send Request',
    quoteDetails: 'Quote Details',
    cargoType: 'Cargo Type',
    preferredDate: 'Preferred Date',
    additionalNotes: 'Additional Notes',
    requestSentSuccess: 'Request sent successfully!',
    companyAbout: 'About Us',
    services: 'Services',
    operatingPorts: 'Operating Ports',
    mainBranch: 'Main Branch',
    // Auth & Profile
    login: 'Login',
    logout: 'Sign Out',
    signup: 'Sign Up',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    alreadyHaveAccount: 'Have an account?',
    dontHaveAccount: "New here?",
    createAccount: 'Create Account',
    premiumFeature: 'Premium',
    unlockAllFeatures: 'Upgrade to unlock full potential.',
    subscribeNow: 'Subscribe',
    name: 'Name',
    loginWelcome: 'Welcome Back',
    loginSubtext: 'Access your dashboard.',
    registerWelcome: 'Get Started',
    registerSubtext: 'Join the network.',
    profileTitle: 'Account',
    subscriptionStatus: 'Plan',
    currentPlan: 'Current',
    yourCurrentPlan: 'Your Plan',
    expiresOn: 'Renews',
    upgradeSubscription: 'Upgrade',
    manageSubscription: 'Manage',
    notSubscribed: 'Free Tier',
    chooseAPlan: 'Select a plan',
    subscribedTo: 'Subscribed to {planName}',
    activityOverview: 'Activity Overview',
    operationsToday: 'Operations Today',
    operationsMonth: 'Operations This Month',
    totalShipments: 'Total Shipments',
    activeShipments: 'Active Shipments',
    completedShipments: 'Completed',
    estimatedProfit: 'Est. Profit',
    savedRoutesCount: 'Saved Routes',
    totalRevenue: 'Total Revenue',
    viewDashboard: 'Dashboard',
    myShipments: 'My Shipments',
    accountSettings: 'Account Settings',
    // Auth - New
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    enterEmailToReset: 'Enter your email to receive reset instructions.',
    resetEmailSent: 'Password reset email sent!',
    sendResetLink: 'Send Reset Link',
    rememberMe: 'Remember me',
    loginWithGoogle: 'Login with Google',
    or: 'Or',
    // Contact Us
    contactFormTitle: 'Get in Touch',
    contactFormSubtitle: 'We are here to help with any inquiries.',
    yourName: 'Name',
    yourEmail: 'Email',
    message: 'Message',
    sendMessage: 'Send',
    messageSent: 'Sent!',
    messageSentDesc: 'We will reply shortly.',
    emailSupportTitle: 'Email',
    emailAddress: 'support@logisticsbarab.com',
    phoneSupportTitle: 'Phone',
    phoneNumber: '+20 123 456 7890',
    // Invoice Generator
    invoiceAndPackingList: 'Trade Docs Generator',
    invoiceAndPackingListSubtitle: 'Generate standardized Commercial Invoices and Packing Lists.',
    logoAndSeal: 'Branding',
    companyLogo: 'Logo',
    logoPlaceholder: 'Upload Logo',
    companySeal: 'Seal/Signature',
    sealPlaceholder: 'Upload Seal',
    exporterDetails: 'Exporter',
    exporterName: 'Exporter Name',
    exporterAddress: 'Exporter Address',
    importerDetails: 'Importer',
    importerName: 'Importer Name',
    importerAddress: 'Importer Address',
    invoiceAndShipmentDetails: 'Shipment Data',
    invoiceNo: 'Invoice #',
    invoiceDate: 'Date',
    packingIn: 'Packing',
    pol: 'P.O.L',
    pod: 'P.O.D',
    incoterm: 'Incoterm',
    bankDetails: 'Banking Info',
    advisingBank: 'Advising Bank',
    bankName: 'Bank Name',
    accountName: 'Account Name',
    swiftCode: 'Swift Code',
    iban: 'IBAN',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    updateItem: 'Update',
    itemDescription: 'Description',
    packagesCount: 'Pkg Count',
    packageUnit: 'Unit',
    netWtPerUnit: 'Net/Unit',
    totalNetWt: 'Total Net',
    grossWtPerUnit: 'Gross/Unit',
    totalGrossWt: 'Total Gross',
    pricePerKgs: 'Price/Unit',
    delete: 'Delete',
    edit: 'Edit',
    // Shipping Forms
    selectForm: 'Select Document Type',
    billOfLading: 'Bill of Lading',
    commercialInvoice: 'Commercial Invoice',
    shipperExporter: 'Shipper',
    consignee: 'Consignee',
    notifyParty: 'Notify',
    vesselVoyage: 'Vessel / Voyage',
    portOfLoading: 'Port of Loading',
    portOfDischarge: 'Port of Discharge',
    placeOfReceipt: 'Receipt Place',
    placeOfDelivery: 'Delivery Place',
    marksAndNumbers: 'Marks & Nos',
    noOfContainers: 'No. Containers',
    kindOfPackages: 'Pkg Kind',
    descriptionOfGoods: 'Goods Description',
    grossWeight: 'Gross Wt (KGS)',
    measurement: 'Measure (CBM)',
    // Shipping Forms - Preview
    shippingDeclaration: 'Shipping Declaration',
    finalShippingDeclaration: 'Final Shipping Declaration',
    cityInDate: 'Issued At/Date',
    shipperNameAddress: 'Shipper Details',
    consigneeNameAddress: 'Consignee Details',
    notifyNameAddress: 'Notify Details',
    blOriginalCopy: 'B/L Counts',
    netWeight: 'Net Wt',
    signatureAndStamp: 'Signature',
    // Shipment Tracker
    addShipment: 'New Shipment',
    trackShipment: 'Track',
    shipmentId: 'Ref / B/L No.',
    status: 'Status',
    customer: 'Customer',
    driver: 'Driver',
    vehicle: 'Truck/Vehicle',
    progress: 'Progress',
    eta: 'ETA',
    updates: 'Log',
    nextCheckpoint: 'Next Step',
    pending: 'Pending',
    assigned: 'Assigned',
    in_transit: 'In Transit',
    delivered: 'Delivered',
    pickup_order_issued: 'Pickup Order',
    driver_assigned_for_pickup: 'Driver for Pickup',
    container_picked_up: 'Container Picked',
    at_shipper_for_loading: 'At Loading',
    loading_complete_enroute_to_port: 'En Route to Port',
    documents_submitted: 'Docs Submitted',
    customs_clearance_export: 'Export Customs',
    customs_clearance_import: 'Import Customs',
    ready_for_delivery: 'Ready for Del.',
    noShipments: 'No active shipments.',
    shipmentDetails: 'Details',
    backToDashboard: 'Dashboard',
    assignDriverAndVehicle: 'Assign Transport',
    startShipment: 'Start Voyage',
    updateLocation: 'Location',
    markAsDelivered: 'Complete Delivery',
    driverId: 'Driver ID',
    vehicleId: 'Vehicle ID',
    assign: 'Assign',
    currentLocation: 'Location',
    update: 'Update',
    confirmDelivery: 'Confirm delivery completion?',
    confirm: 'Confirm',
    shipmentWeight: 'Weight',
    shipmentValue: 'Value',
    shipmentTimeline: 'Timeline',
    shipmentAdded: 'Created',
    driverAssigned: 'Driver Assigned',
    shipmentStarted: 'Started',
    arrivedAt: 'Arrived',
    shipmentDelivered: 'Delivered',
    issuePickupOrder: 'Issue Pickup',
    assignDriverForPickup: 'Assign Pickup',
    confirmContainerPickup: 'Confirm Pickup',
    confirmArrivalAtShipper: 'Confirm Arrival',
    markLoadingComplete: 'Loading Done',
    containerId: 'Container #',
    pickupOrderIssued: 'Pickup Issued',
    driverAssignedForPickup: 'Pickup Driver Assigned',
    containerPickedUp: 'Container Picked',
    arrivedAtShipper: 'Arrived at Shipper',
    loadingComplete: 'Loading Complete',
    oceanTransitStarted: 'Transit Started',
    preTransitDetails: 'Pre-Transit',
    setEta: 'Set ETA',
    estimatedArrivalTime: 'ETA',
    delayAlert: 'Delay',
    noDelay: 'On Time',
    shipmentDelayed: 'Delayed',
    vesselAndVoyage: 'Vessel Info',
    vesselName: 'Vessel',
    voyageNumber: 'Voyage',
    keyDates: 'Schedule',
    estimatedDeparture: 'ETD',
    actualDeparture: 'ATD',
    actualArrival: 'ATA',
    documents: 'Docs',
    noDocuments: 'No docs.',
    uploadDocument: 'Upload',
    documentName: 'Name',
    documentType: 'Type',
    temperatureControlled: 'Reefer',
    temperatureSetting: 'Temp (°C)',
    reeferMonitoring: 'Monitoring',
    submitDocuments: 'Submit Docs',
    startExportClearance: 'Export Clear.',
    logVesselDeparture: 'Log Departure',
    startImportClearance: 'Import Clear.',
    markReadyForDelivery: 'Ready for Del.',
    logDepartureTime: 'Log ATD',
    logArrivalTime: 'Log ATA',
    documentsSubmitted: 'Docs Submitted',
    exportClearanceStarted: 'Exp. Clearance',
    vesselDeparted: 'Vessel Departed',
    importClearanceStarted: 'Imp. Clearance',
    shipmentReadyForDelivery: 'Cleared & Ready',
    shipmentInfo: 'Shipment',
    logisticsInfo: 'Logistics',
    driverAndVehicleInfo: 'Transport',
    shippingLine: 'Line',
    bookingNo: 'Booking #',
    containerSize: 'Size',
    sealNo: 'Seal #',
    driverName: 'Driver',
    driverPhone: 'Phone',
    truckPlate: 'Truck',
    trailerPlate: 'Trailer',
    addShipmentUpdate: 'Add Note',
    enterUpdateMessage: 'Message...',
    addUpdate: 'Add',
    customsBroker: 'Customs Broker',
    customsBrokerName: 'Customs Broker Name',
    transportCompany: 'Transport Company',
    importFromChat: 'Import from Chat',
    pasteChatHere: 'Paste logistics chat log here (WhatsApp, etc.)...',
    parseChat: 'Parse Data',
    analyzing: 'Analyzing...',
    shipmentsFound: 'Shipments Found',
    import: 'Import',
    saveAll: 'Save All',
    // New keys
    loadDataFromShipment: 'Load from Shipment',
    loadFromShipment: 'Load',
    shipmentNotFound: 'ID "{shipmentId}" not found.',
    dataLoadedSuccess: 'Loaded {shipmentId}',
    previewInEnglish: 'Preview EN',
    previewInArabic: 'Preview AR',
    switchedToPreview: 'Preview: {lang}',
    financeInfo: 'Financials',
    cost: 'Purchase Price',
    price: 'Sale Price',
    profit: 'Profit',
    editShipment: 'Edit',
    saveChanges: 'Save',
    certType: 'Certificate',
    certificateOfOrigin: 'Cert. of Origin',
    phytosanitaryCertificate: 'Phytosanitary',
    leagueOfArabStates: 'Arab League',
    parties: 'Parties',
    exporterNameAddressCountry: '1. Exporter',
    importerNameAddressCountry: '2. Importer',
    producerAndAddress: 'Producer',
    certNo: 'Cert #',
    portOfShipmentOptional: 'Port of Shipment',
    vessel: 'Vessel',
    blNo: 'B/L No.',
    from: 'From',
    to: 'To',
    date: 'Date',
    commercialInvoiceNoAndDate: 'Inv No & Date',
    countryOfOrigin: 'Origin',
    countryOfDestination: 'Destination',
    goodsAndMeasures: 'Goods',
    number: '#',
    numCategoriesOfParcels: 'Pkgs',
    grossMassKg: 'Gross (kg)',
    statementByExporter: 'Exporter Statement',
    certifyGoodsOfOrigin: 'Certification',
    agriCertPlaceholder: 'Coming soon.',
    officialPreview: 'Preview',
    enterDocumentData: 'Input Data',
    phytoNo: 'No.',
    phytoTo: '1. To',
    phytoExporter: '2. Exporter',
    phytoConsignee: '3. Consignee',
    phytoConveyance: '4. Conveyance',
    phytoEntryPoint: '5. Entry Point',
    phytoPlaceOfOrigin: '6. Origin',
    phytoDistinguishingMarks: '7. Marks',
    phytoNumAndDesc: '8. Number/Desc',
    phytoNameOfProduce: '9. Produce Name',
    phytoBotanicalName: '10. Botanical',
    phytoCertificationText: '11. Cert Text',
    phytoTreatment: '12. Treatment',
    phytoChemical: '13. Chemical',
    phytoConcentration: '14. Conc.',
    phytoDurationTemp: '15. Dur/Temp',
    phytoAddInfo: '16. Info',
    phytoAddDeclaration: '17. Declaration',
    phytoInspectionDate: '18. Insp. Date',
    phytoIssueDate: '19. Issue Date',
    phytoIssuePlace: '20. Issue Place',
    phytoInspectorName: '21. Inspector',
    phytoAuthOfficerName: '22. Officer',
    phytoPortOfLoading: '23. P.O.L',
    phytoStamp: '24. Stamp',
    phytoSignature: '25. Signature',
    routePlannerDesc: 'AI-optimized sea routes.',
    hsCodeFinderDesc: 'Instant code classification.',
    invoiceGeneratorDesc: 'Professional trade docs.',
    shippingFormsDesc: 'Standard declarations.',
    shipmentTrackerDesc: 'Live milestone tracking.',
    documentEditorDesc: 'Official certificates.',
    pricingSubtitle: 'Flexible plans for growing businesses.',
    monthlyPlan: 'Monthly',
    yearlyPlan: 'Yearly',
    monthlyPrice: '250',
    yearlyPrice: '2400',
    currency: 'EGP',
    perMonth: '/mo',
    perYear: '/yr',
    savePrice: 'Save',
    billedMonthly: 'Billed monthly',
    billedYearly: 'Billed yearly',
    planFeatures: 'Includes:',
    feature1: 'AI Route Planner',
    feature2: 'HS Code Finder',
    feature3: 'Doc Generators',
    feature4: 'Shipment Tracker',
    feature5: 'Directory Access',
    mostPopular: 'Best Value',
    tariffItem: 'Tariff Item',
    originCriterion: 'Origin Criterion',
    remarks: 'Remarks',
    cumulationApplied: 'Cumulation applied',
    issuedRetrospectively: 'ISSUED RETROSPECTIVELY',
    duplicate: 'DUPLICATE',
    transportDetails: 'Transport Details',
    previewSettings: 'Preview & Print Settings',
    fontSize: 'Font Size (pt)',
    pageWidth: 'Page Width (mm)',
    pageHeight: 'Page Height (mm)',
    resetSettings: 'Reset Default',
    requiredField: 'This field is required',
    invalidEmail: 'Invalid email address',
    atLeastOnePort: 'Please enter at least one port',
    searchShipmentsPlaceholder: 'Search Ref, Exporter, Broker, Ports...',
    filterByDate: 'Filter by Date',
    allDates: 'All Time',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    // Document Formatting
    formatting: 'Formatting',
    fontSizeLabel: 'Font Size',
    alignmentLabel: 'Alignment',
    increaseFont: 'Increase Font',
    decreaseFont: 'Decrease Font',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    // Knowledge and Directory
    knowledgeSectionTitle: 'Knowledge Base',
    knowledgeSectionDesc: 'A continually updated information engine covering port news, customs regulations, and modern technologies with a focus on the Arab region.',
    directorySectionTitle: 'Company Directory',
    directorySectionDesc: 'Search a selected list of shipping lines, freight forwarders, brokers, and certified customs brokers.',
    knowledgeCard1Title: 'Port Monitoring',
    knowledgeCard1Desc: 'Daily alerts on congestion, closures, and weather conditions in major Middle East ports.',
    knowledgeCard2Title: 'Compliance Guides',
    knowledgeCard2Desc: 'Detailed procedures for customs compliance in the Gulf, Levant, and North Africa backed by official references.',
    knowledgeCard3Title: 'Tech & Innovation',
    knowledgeCard3Desc: 'Analyses on AI adoption, visibility platforms, and digital transformation solutions for the maritime sector.',
    directoryCard1Title: 'Shipping Lines',
    directoryCard1Desc: 'Container, Ro-Ro, and bulk vessels serving major Arab ports.',
    directoryCard2Title: 'Freight Forwarders',
    directoryCard2Desc: 'Comprehensive partners with local expertise and value-added services for the shipping journey.',
    directoryCard3Title: 'Brokers & Agents',
    directoryCard3Desc: 'Specialists in vessel chartering, documentation, and maritime agency services.',
    // Profile - Sidebar & Settings
    notifications: 'Notifications',
    helpAndSupport: 'Help & Support',
    security: 'Security',
    notificationsSettings: 'Notification Preferences',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    appUpdates: 'App Updates',
    faqs: 'Frequently Asked Questions',
    contactSupport: 'Contact Support',
    receiveEmails: 'Receive emails about shipment updates',
    receiveSms: 'Receive SMS for critical alerts',
    receiveAppUpdates: 'Receive news about new features',
    privacyPolicy: 'Privacy Policy',
    termsAndConditions: 'Terms & Conditions',
    commonQuestions: 'Common questions about shipping, tracking, and payments.',
    reachSupportTeam: 'Reach out to our support team via email or phone.',
    legalInformation: 'Legal information and user agreements.',
    dataProtection: 'Data protection and privacy policies.',
    // New Customs Expense Terms
    operationNumber: 'Operation No.',
    certificateNumber: 'Certificate No.',
    agriculturalInspection: 'Agricultural Inspection',
    foodSafety: 'Food Safety Authority',
    nathria: 'Petty Expenses (Nathria)',
    mashal: 'Porterage/Handling (Mashal)',
    officialReceipts: 'Official Receipts',
    clearanceFees: 'Clearance Fees',
    doorInspection: 'Door Inspection',
    expensesBreakdown: 'Expenses Breakdown',
    printMode: 'Print Mode',
    fullDocument: 'Full Document',
    dataOnly: 'Data Only',
    margins: 'Page Margins',
    marginTop: 'Top Margin',
    marginLeft: 'Left Margin',
    baseFontSize: 'Base Font Size',
    uploadPhoto: 'Upload Photo',
    companyDetails: 'Company Details',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    profileUpdated: 'Profile updated successfully!',
    // Keys for Sidebar & Author Info
    youMightLike: 'You Might Also Like',
    weeklyLogisticsBrief: 'Weekly Logistics Brief',
    getMarketUpdates: 'Get the latest market updates delivered to your inbox.',
    editorialTeam: 'Logistics B Arabc Editorial',
    marketIntelligence: 'Market Intelligence Team',
  },
  ar: {
    loading: 'جار التحميل...',
    close: 'إغلاق',
    submit: 'إرسال',
    save: 'حفظ',
    share: 'مشاركة',
    printOrSave: 'طباعة / PDF',
    downloadPdf: 'تحميل PDF',
    readMore: 'أكمل القراءة',
    showLess: 'عرض أقل',
    viewDetails: 'التفاصيل',
    back: 'رجوع',
    cancel: 'إلغاء',
    talkWithUs: 'تحدث معنا',
    actions: 'إجراءات',
    saveDraft: 'حفظ مسودة',
    loadDraft: 'تحميل مسودة',
    clearForm: 'مسح النموذج',
    draftSaved: 'تم الحفظ بنجاح',
    draftLoaded: 'تم تحميل المسودة',
    formCleared: 'تم مسح البيانات',
    confirmLoad: 'هل تود تحميل المسودة المحفوظة؟ سيتم استبدال البيانات الحالية.',
    confirmClear: 'هل أنت متأكد من مسح النموذج؟ ستفقد كافة البيانات المدخلة.',
    foundSavedDraft: 'وجدنا مسودة محفوظة، هل ترغب في استعادتها؟',
    confirmDeleteDocument: 'هل أنت متأكد أنك تريد حذف "{docName}"؟',
    confirmDeleteItem: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    confirmDeleteShipment: 'هل أنت متأكد أنك تريد حذف الشحنة {id}؟',
    confirmDeleteRoute: 'هل أنت متأكد أنك تريد حذف هذا المسار؟',
    confirmDeleteUser: 'هل أنت متأكد أنك تريد حذف المستخدم {email}؟',
    confirmDeleteArticle: 'هل أنت متأكد أنك تريد حذف هذا المقال؟',
    confirmDeleteCompany: 'هل أنت متأكد أنك تريد حذف شركة {name}؟',
    home: 'الرئيسية',
    articles: 'المقالات والأخبار',
    tools: 'الأدوات الذكية',
    knowledgeBase: 'مركز المعرفة',
    directory: 'دليل الشركات',
    routePlanner: 'المستشار الملاحي',
    hsCodeFinder: 'مكتشف البند الجمركي',
    invoiceGenerator: 'منشئ الوثائق',
    shippingForms: 'نماذج الشحن',
    shipmentTracker: 'إدارة الشحنات',
    documentEditor: 'محرر الشهادات',
    contactUs: 'اتصل بنا',
    profile: 'الملف الشخصي',
    pricing: 'الباقات والأسعار',
    privacy: 'سياسة الخصوصية',
    terms: 'الشروط والأحكام',
    faq: 'الأسئلة الشائعة',
    // Footer Specific - Arabic
    quickLinks: 'روابط سريعة',
    supportLegal: 'الدعم والقانونية',
    aboutUs: 'من نحن',
    ourServices: 'خدماتنا',
    blog: 'المدونة',
    refundPolicy: 'سياسة الاسترجاع',
    newsletterTitle: 'كن في قلب الحدث',
    newsletterDesc: 'اشترك في نشرتنا البريدية لتصلك أحدث تحليلات السوق وأخبار الموانئ.',
    subscribe: 'اشتراك',
    addressLabel: 'القاهرة، مصر - المنطقة الحرة العامة',
    paymentMethods: 'طرق الدفع الآمنة',
    brandName: 'Logistics B Arabc',
    knowledgeBridgeTag: 'جسر المعرفة • تجارة ذكية • هوية عربية',
    heroTitle_new: 'المنصة العربية الذكية للخدمات اللوجستية',
    heroSubtitle_new: 'نجمع بين قوة الذكاء الاصطناعي وخبرة السوق المحلي لتمكين أعمالك. خطط مساراتك، أصدر وثائقك، وتواصل مع شركاء النجاح في مكان واحد.',
    heroCardTitle: 'ذكاء لوجستي متكامل',
    heroCardSubtitle: 'توحيد استشارات الذكاء الاصطناعي مع الأتمتة والخبرة البشرية لكل قرار شحن.',
    heroCardRoute: 'جدة ← روتردام',
    heroCardRouteDesc: 'تنبيهات البحر الأحمر مفعلة • المسار الموصى به عبر رأس الرجاء الصالح',
    heroCardHs: 'HS 8418.69 — وحدات تبريد',
    heroCardHsDesc: 'رسوم مبسطة للسعودية والإمارات • قائمة تحقق جاهزة',
    logisticsHubTitle: 'مركز الخدمات اللوجستية',
    heroCta1: 'جرب الأدوات الذكية',
    heroCta2: 'تصفح الدليل',
    alertRouteLabel: 'تنبيه مسار مباشر',
    alertCustomsLabel: 'لمحة جمركية',
    dashboardLive: 'مباشر',
    dashboardAnalysis: 'تحليل Gemini',
    dashboardStats: 'نشاط النظام',
    stat1: 'مسارات محسنة',
    stat2: 'شركات شريكة',
    stat3: 'مقالات معرفية',
    stat4: 'خبراء موثقون',
    poweredByAI: 'مدعوم بتقنيات Gemini AI',
    howItWorksTitle: 'رحلة الشحن.. أسهل وأذكى',
    howItWorksSubtitle: 'نحول التعقيدات اللوجستية إلى خطوات منظمة تبدأ من التخطيط وتنتهي بالتسليم، مع ضمان الامتثال الكامل.',
    howItWorks1Title: 'إدارة العمليات',
    howItWorks1Desc: 'وثّق شحناتك، أصدر الفواتير بضغطة زر، وراقب كل مرحلة بدقة متناهية.',
    howItWorks2Title: 'شبكة الشركاء',
    howItWorks2Desc: 'دليل شامل يضم نخبة خطوط الشحن، والمخلصين الجمركيين، ووكلاء الشحن الموثوقين.',
    howItWorks3Title: 'الأدوات الذكية',
    howItWorks3Desc: 'تقنيات متطورة مصممة خصيصاً لخدمة المصدر والمستورد العربي.',
    poweredByGemini: 'مدعوم من Gemini AI',
    toolsTitle: 'تقنيات ذكية لقرارات لوجستية أدق',
    toolsSubtitle: 'مجموعة أدوات متطورة تتصل بقاعدة بيانات حية لتمنحك القدرة على التخطيط، التسعير، والتنفيذ بكفاءة عالية.',
    tools1Desc: 'نظام ملاحي ذكي يحلل المتغيرات الجيوسياسية والطقس لاقتراح المسارات الأكثر أماناً وكفاءة.',
    tools2Desc: 'مُصنف جمركي فوري يفهم المصطلحات التجارية الدارجة ويحولها إلى أكواد منسقة بدقة عالية.',
    tools3Desc: 'مُولد مستندات احترافي يضمن الامتثال للمعايير الدولية، مع إمكانية التخصيص والتصدير الفوري.',
    tools4Desc: 'لوحة تحكم مركزية لمتابعة حركة الشحنات، المصروفات، وتحديثات الحالة لحظة بلحظة.',
    communityInsights: 'أصوات من القطاع',
    communityInsightsDesc: '',
    latestArticles: 'أحدث التحليلات والأخبار',
    viewAllArticles: 'تصفح قاعدة المعرفة',
    testimonial1: "أداة البحث عن البند الجمركي وفرت علينا ساعات من العمل اليدوي. دقة النتائج باللغتين مذهلة.",
    testimonial1_author: "أخصائي استيراد وتصدير",
    testimonial1_role: "قطاع التجزئة",
    testimonial2: "أصبحت Logistics B Arabc المرجع الأول لنا لفهم السوق الإقليمي وتجنب مخاطر التأخير.",
    testimonial2_author: "مدير لوجستي",
    testimonial2_role: "شركة تصدير كبرى",
    ctaTitle: 'ابدأ رحلة التحول الرقمي اليوم',
    ctaSubtitle: 'انضم لآلاف المحترفين الذين يعتمدون على Logistics B Arabc لتبسيط عملياتهم.',
    startNow: 'ابدأ مجاناً',
    specialThanksTitle: 'شريك استراتيجي',
    specialThanksDesc: 'نقدر الدور الريادي للمجموعة الدولية للوجستيات (IGL) في دعم التحول الرقمي في المنطقة.',
    viewPartner: 'ملف الشريك',
    footerSubtitle_new: 'بوابتك الرقمية لعالم اللوجستيات في الشرق الأوسط وأفريقيا.',
    footerLinksExplore: 'استكشف',
    subscribeToUpdates: 'تواصل معنا',
    subscribeToUpdatesDesc_new: 'احصل على آخر أخبار الملاحة وتحديثات المنصة في بريدك.',
    enterYourEmail: 'بريدك الإلكتروني',
    subscribe_new: 'اشتراك',
    footerRights: 'جميع الحقوق محفوظة',
    english: 'English',
    arabic: 'العربية',
    origin: 'ميناء القيام (POL)',
    destination: 'ميناء الوصول (POD)',
    goodsDescription: 'وصف البضاعة',
    getAdvice: 'تحليل المسار',
    shippingAdvice: 'التحليل الذكي والتوصيات',
    shipmentType: 'نوع الشحنة',
    quantityWeightVolume: 'الكمية / الوزن',
    fcl: 'حاوية كاملة (FCL)',
    lcl: 'شحنة جزئية (LCL)',
    saveAdvice: 'حفظ التقرير',
    adviceSaved: 'تم الحفظ في الأرشيف',
    savedAdvice: 'التقارير المحفوظة',
    noSavedAdvice: 'لا توجد تقارير محفوظة.',
    viewAdvice: 'عرض التقرير',
    deleteAdvice: 'حذف',
    groundingSources: 'المصادر الموثقة (خرائط جوجل)',
    saveRoute: 'حفظ المسار',
    loadRoute: 'تحميل مسار',
    savedRoutes: 'المسارات المفضلة',
    routeName: 'اسم المسار',
    noSavedRoutes: 'لا توجد مسارات محفوظة.',
    enterRouteName: 'أدخل اسم المسار',
    routeSaved: 'تم حفظ المسار بنجاح',
    pickupDate: 'تاريخ التحميل المتوقع',
    expectedDepartureDate: 'تاريخ المغادرة المتوقع',
    productDescription: 'صف المنتج (مثال: "جمبري مجمد"، "قمصان قطنية")',
    findHSCode: 'تحليل وتصنيف',
    hsCodeSuggestions: 'البنود الجمركية المقترحة',
    recentSearches: 'سجل البحث',
    knowledgeBaseHeroTitle: 'قاعدة المعرفة اللوجستية',
    knowledgeBaseHeroSubtitle: 'محرك بحثي متجدد يغطي أخبار الموانئ، والتشريعات الجمركية، والاتجاهات العالمية مع تركيز خاص على المنطقة العربية.',
    searchArticles: 'ابحث في المقالات...',
    logisticsDictionary: 'قاموس المصطلحات',
    dictionaryDesc: 'شرح مبسط للمصطلحات البحرية والتجارية (Incoterms).',
    lawsAndRegulations: 'القوانين والتشريعات',
    lawsDesc: 'أحدث التعديلات في قوانين الجمارك والاستيراد.',
    'sea-freight': 'الشحن البحري',
    'customs': 'الجمارك والتخليص',
    'ports': 'أخبار الموانئ',
    'news': 'أخبار السوق',
    'logistics-tech': 'تكنولوجيا اللوجستيات',
    'warehousing': 'التخزين والتوزيع',
    'global-trade': 'التجارة الدولية',
    'financial': 'المالية والمدفوعات',
    'educational': 'أكاديمية اللوجستيات',
    'laws-and-regulations': 'دليل الامتثال',
    addCompany: 'أضف شركتك',
    searchByName: 'ابحث عن شركات، خدمات، أو موانئ...',
    searchByPort: 'تصفية حسب الميناء...',
    allCategories: 'كل التصنيفات',
    selectCompanyType: 'تصنيف الشركة',
    companyName: 'اسم الشركة',
    companyNameAr: 'اسم الشركة (عربي)',
    companyNameEn: 'اسم الشركة (إنجليزي)',
    companyWebsite: 'الموقع الإلكتروني',
    verificationDocument: 'السجل التجاري / البطاقة الضريبية',
    uploadVerification: 'رفع المستند (PDF/صورة)',
    companyAddedSuccess: 'تم إرسال طلبك بنجاح! سيتم مراجعة البيانات وتفعيل الحساب قريباً.',
    companyDescription: 'نبذة عن الشركة',
    contactInfo: 'بيانات الاتصال',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    category: 'التصنيف',
    sortBy: 'ترتيب حسب',
    sortName: 'الاسم',
    sortCategory: 'التصنيف',
    commercialRegistration: 'السجل التجاري',
    uploadFile: 'رفع ملف',
    fileTooLarge: 'حجم الملف يتجاوز 5 ميجابايت.',
    branchDetails: 'الفروع',
    workingHours: 'ساعات العمل',
    peakTimes: 'مؤشر الازدحام',
    peakTimeSlot1: '٨-١٠ص',
    peakTimeSlot2: '١٠-١٢ظ',
    peakTimeSlot3: '١٢-٢ظ',
    peakTimeSlot4: '٢-٤م',
    peakTimeSlot5: '٤-٦م',
    busynessLevel: 'مستوى النشاط: {level}/5',
    importantServiceAreas: 'المسارات الرئيسية',
    featuredAreas: 'خدمات تخصصية',
    generateEmail: 'إنشاء بريد إلكتروني',
    contactCompany: 'تواصل مع الشركة',
    emailSubject: 'استفسار تجاري - Logistics B Arabc',
    emailBody: 'السادة فريق العمل المحترمين،\n\nنحن مهتمون بخدماتكم اللوجستية ونرغب في مناقشة سبل التعاون.\n\nوتفضلوا بقبول فائق الاحترام،',
    companySubmitted: 'تم الإرسال',
    companySubmittedDesc: 'طلبك قيد المراجعة.',
    loginToView: 'سجل الدخول لعرض التفاصيل',
    'shipping-line': 'خطوط ملاحية',
    'freight-forwarder': 'وكلاء شحن (Freight Forwarders)',
    'transportation': 'نقل بري وشاحنات',
    'customs-broker': 'تخليص جمركي',
    myFavorites: 'المفضلة',
    addToFavorites: 'إضافة للمفضلة',
    removeFromFavorites: 'إزالة من المفضلة',
    noFavorites: 'لم تقم بإضافة أي شركات للمفضلة بعد.',
    rateThisCompany: 'شارك تقييمك',
    yourRating: 'تقييمك',
    averageRating: 'متوسط التقييم',
    noRatingsYet: 'لا توجد تقييمات بعد',
    ratingsCount: '({count} تقييم)',
    reviews: 'آراء العملاء',
    writeReview: 'اكتب رأيك',
    ratingCommentPlaceholder: 'شارك تجربتك مع المجتمع اللوجستي...',
    submitReview: 'نشر التقييم',
    resetFilters: 'مسح التصنيفات',
    verified: 'حساب موثق',
    visitWebsite: 'زيارة الموقع',
    callNow: 'اتصال',
    directoryStats: 'شبكة الشركاء',
    totalCompanies: 'شركة مسجلة',
    requestQuote: 'طلب عرض سعر',
    sendRequest: 'إرسال الطلب',
    quoteDetails: 'تفاصيل الطلب',
    cargoType: 'نوع البضاعة',
    preferredDate: 'تاريخ الشحن المفضل',
    additionalNotes: 'ملاحظات إضافية',
    requestSentSuccess: 'تم إرسال طلب عرض السعر بنجاح!',
    companyAbout: 'عن الشركة',
    services: 'الخدمات المقدمة',
    operatingPorts: 'نطاق التشغيل (الموانئ)',
    mainBranch: 'الفرع الرئيسي',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    signup: 'إنشاء حساب',
    register: 'حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    dontHaveAccount: 'مستخدم جديد؟',
    createAccount: 'إنشاء حساب جديد',
    premiumFeature: 'ميزة مدفوعة',
    unlockAllFeatures: 'اشترك الآن لفتح كافة المميزات الاحترافية.',
    subscribeNow: 'ترقية الاشتراك',
    name: 'الاسم الكامل',
    loginWelcome: 'مرحباً بعودتك',
    loginSubtext: 'سجل الدخول لمتابعة أعمالك.',
    registerWelcome: 'انضم إلينا',
    registerSubtext: 'كن جزءاً من أكبر مجتمع لوجستي عربي.',
    profileTitle: 'الملف الشخصي',
    subscriptionStatus: 'حالة الاشتراك',
    currentPlan: 'الخطة الحالية',
    yourCurrentPlan: 'باقتك',
    expiresOn: 'تاريخ التجديد',
    upgradeSubscription: 'ترقية',
    manageSubscription: 'إدارة الاشتراك',
    notSubscribed: 'الباقة المجانية',
    chooseAPlan: 'اختر الباقة المناسبة',
    subscribedTo: 'مشترك في باقة {planName}',
    activityOverview: 'نظرة عامة على النشاط',
    operationsToday: 'عمليات اليوم',
    operationsMonth: 'أداء الشهر الحالي',
    totalShipments: 'إجمالي الشحنات',
    activeShipments: 'شحنات قيد التنفيذ',
    completedShipments: 'شحنات مكتملة',
    estimatedProfit: 'الأرباح المقدرة',
    savedRoutesCount: 'مسارات محفوظة',
    totalRevenue: 'إجمالي الإيرادات',
    viewDashboard: 'لوحة التحكم',
    myShipments: 'سجل الشحنات',
    accountSettings: 'إعدادات الحساب',
    // Auth - New
    forgotPassword: 'نسيت كلمة المرور؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    enterEmailToReset: 'أدخل بريدك الإلكتروني لاستلام رابط الاستعادة.',
    resetEmailSent: 'تم إرسال الرابط بنجاح.',
    sendResetLink: 'إرسال الرابط',
    rememberMe: 'تذكرني',
    loginWithGoogle: 'دخول باستخدام Google',
    or: 'أو',
    // Contact Us
    contactFormTitle: 'تواصل معنا',
    contactFormSubtitle: 'فريق الدعم جاهز للإجابة على استفساراتكم.',
    yourName: 'الاسم',
    yourEmail: 'البريد الإلكتروني',
    message: 'نص الرسالة',
    sendMessage: 'إرسال الرسالة',
    messageSent: 'تم الإرسال بنجاح',
    messageSentDesc: 'شكراً لتواصلك معنا، سنقوم بالرد في أقرب وقت.',
    emailSupportTitle: 'البريد الإلكتروني',
    emailAddress: 'support@logisticsbarab.com',
    phoneSupportTitle: 'الهاتف',
    phoneNumber: '+٢٠ ١٢٣ ٤٥٦ ٧٨٩٠',
    invoiceAndPackingList: 'إنشاء الفواتير وقوائم التعبئة',
    invoiceAndPackingListSubtitle: 'أداة احترافية لإصدار مستندات تجارية مطابقة للمعايير الدولية، مع دعم كامل للغة العربية.',
    logoAndSeal: 'هوية الشركة',
    companyLogo: 'شعار الشركة',
    logoPlaceholder: 'انقر لرفع الشعار',
    companySeal: 'الختم / التوقيع',
    sealPlaceholder: 'انقر لرفع الختم',
    exporterDetails: 'بيانات المصدر (Exporter)',
    exporterName: 'اسم المصدر',
    exporterAddress: 'عنوان المصدر',
    importerDetails: 'بيانات المستورد (Importer)',
    importerName: 'اسم المستورد',
    importerAddress: 'عنوان المستورد',
    invoiceAndShipmentDetails: 'تفاصيل الشحنة والفاتورة',
    invoiceNo: 'رقم الفاتورة',
    invoiceDate: 'تاريخ الإصدار',
    packingIn: 'طريقة التعبئة',
    pol: 'ميناء التحميل (POL)',
    pod: 'ميناء الوصول (POD)',
    incoterm: 'شرط الشحن (Incoterm)',
    bankDetails: 'البيانات البنكية',
    advisingBank: 'البنك المُبَلِغ (Advising Bank)',
    bankName: 'اسم البنك',
    accountName: 'اسم الحساب',
    swiftCode: 'كود السويفت (Swift)',
    iban: 'رقم الآيبان (IBAN)',
    addItem: 'إضافة صنف',
    editItem: 'تعديل صنف',
    updateItem: 'حفظ التعديلات',
    itemDescription: 'وصف الصنف',
    packagesCount: 'عدد الطرود',
    packageUnit: 'نوع الطرد',
    netWtPerUnit: 'الوزن الصافي/وحدة',
    totalNetWt: 'إجمالي الصافي',
    grossWtPerUnit: 'الوزن القائم/وحدة',
    totalGrossWt: 'إجمالي القائم',
    pricePerKgs: 'السعر',
    delete: 'حذف',
    edit: 'تحرير',
    selectForm: 'نوع الوثيقة',
    billOfLading: 'بوليصة شحن',
    commercialInvoice: 'فاتورة تجارية',
    shipperExporter: 'الشاحن (Shipper)',
    consignee: 'المرسل إليه (Consignee)',
    notifyParty: 'الطرف المُخطر (Notify Party)',
    vesselVoyage: 'اسم السفينة / رقم الرحلة',
    portOfLoading: 'ميناء التحميل',
    portOfDischarge: 'ميناء التفريغ',
    placeOfReceipt: 'مكان الاستلام',
    placeOfDelivery: 'مكان التسليم النهائي',
    marksAndNumbers: 'العلامات والأرقام',
    noOfContainers: 'عدد الحاويات',
    kindOfPackages: 'نوع الطرود',
    descriptionOfGoods: 'وصف البضائع',
    grossWeight: 'الوزن القائم (KGM)',
    measurement: 'الحجم (CBM)',
    shippingDeclaration: 'إقرار شحن (Shipping Declaration)',
    finalShippingDeclaration: 'إقرار شحن نهائي (Final Shipping Declaration)',
    cityInDate: 'تاريخ ومكان الإصدار',
    shipperNameAddress: 'بيانات الشاحن',
    consigneeNameAddress: 'بيانات المرسل إليه',
    notifyNameAddress: 'بيانات المُخطر',
    blOriginalCopy: 'عدد النسخ (أصلية / صور)',
    netWeight: 'الوزن الصافي',
    signatureAndStamp: 'التوقيع والختم',
    addShipment: 'إضافة شحنة جديدة',
    trackShipment: 'تتبع الشحنات',
    shipmentId: 'رقم الشحنة / البوليصة',
    status: 'الحالة الحالية',
    customer: 'العميل',
    driver: 'السائق',
    vehicle: 'المركبة',
    progress: 'مؤشر التقدم',
    eta: 'وقت الوصول المتوقع (ETA)',
    updates: 'سجل التحديثات',
    nextCheckpoint: 'الخطوة التالية',
    pending: 'قيد الانتظار',
    assigned: 'تم التعيين',
    in_transit: 'في الطريق',
    delivered: 'تم التسليم',
    pickup_order_issued: 'صدر أمر الشحن',
    driver_assigned_for_pickup: 'تعيين سائق للسحب',
    container_picked_up: 'تم سحب الحاوية',
    at_shipper_for_loading: 'وصلت للتحميل',
    loading_complete_enroute_to_port: 'تم التحميل - في الطريق للميناء',
    documents_submitted: 'تم تقديم المستندات',
    customs_clearance_export: 'تخليص جمركي (صادر)',
    customs_clearance_import: 'تخليص جمركي (وارد)',
    ready_for_delivery: 'جاهزة للتسليم',
    noShipments: 'لا توجد شحنات نشطة حالياً.',
    shipmentDetails: 'تفاصيل الشحنة',
    backToDashboard: 'العودة للوحة التحكم',
    assignDriverAndVehicle: 'تعيين السائق والمركبة',
    startShipment: 'بدء الرحلة',
    updateLocation: 'تحديث الموقع',
    markAsDelivered: 'تأكيد التسليم النهائي',
    driverId: 'رقم السائق',
    vehicleId: 'رقم المركبة',
    assign: 'تأكيد التعيين',
    currentLocation: 'الموقع الحالي',
    update: 'إضافة تحديث',
    confirmDelivery: 'هل أنت متأكد من تسليم الشحنة نهائياً؟',
    confirm: 'تأكيد',
    shipmentWeight: 'الوزن الكلي',
    shipmentValue: 'قيمة الشحنة',
    shipmentTimeline: 'المخطط الزمني',
    shipmentAdded: 'تم تسجيل الشحنة',
    driverAssigned: 'تم تعيين السائق',
    shipmentStarted: 'بدأت الرحلة',
    arrivedAt: 'وصلت إلى',
    shipmentDelivered: 'اكتملت العملية',
    issuePickupOrder: 'إصدار أمر استلام',
    assignDriverForPickup: 'توجيه السائق للاستلام',
    confirmContainerPickup: 'تأكيد سحب الحاوية',
    confirmArrivalAtShipper: 'تأكيد الوصول للموقع',
    markLoadingComplete: 'تأكيد انتهاء التحميل',
    containerId: 'رقم الحاوية',
    pickupOrderIssued: 'تم إصدار الأمر',
    driverAssignedForPickup: 'السائق في الطريق',
    containerPickedUp: 'الحاوية مسحوبة',
    arrivedAtShipper: 'عند العميل',
    loadingComplete: 'التحميل مكتمل',
    oceanTransitStarted: 'بدء الإبحار',
    preTransitDetails: 'مرحلة ما قبل الشحن',
    setEta: 'تحديد ETA',
    estimatedArrivalTime: 'موعد الوصول المتوقع',
    delayAlert: 'يوجد تأخير',
    noDelay: 'في الموعد المحدد',
    shipmentDelayed: 'متأخرة',
    vesselAndVoyage: 'تفاصيل الرحلة البحرية',
    vesselName: 'اسم السفينة',
    voyageNumber: 'رقم الرحلة',
    keyDates: 'التواريخ الهامة',
    estimatedDeparture: 'المغادرة المتوقعة (ETD)',
    actualDeparture: 'المغادرة الفعلية (ATD)',
    actualArrival: 'الوصول الفعلي (ATA)',
    documents: 'المستندات المرفقة',
    noDocuments: 'لا توجد مستندات.',
    uploadDocument: 'رفع مستند',
    documentName: 'اسم الملف',
    documentType: 'النوع',
    temperatureControlled: 'شحنة مبردة',
    temperatureSetting: 'درجة الحرارة المطلوبة',
    reeferMonitoring: 'مراقبة التبريد',
    submitDocuments: 'تسليم المستندات',
    startExportClearance: 'بدء التخليص (صادر)',
    logVesselDeparture: 'تسجيل المغادرة',
    startImportClearance: 'بدء التخليص (وارد)',
    markReadyForDelivery: 'الإذن بالتسليم',
    logDepartureTime: 'تسجيل وقت المغادرة',
    logArrivalTime: 'تسجيل وقت الوصول',
    documentsSubmitted: 'المستندات قيد المراجعة',
    exportClearanceStarted: 'التخليص الصادر',
    vesselDeparted: 'السفينة غادرت',
    importClearanceStarted: 'التخليص الوارد',
    shipmentReadyForDelivery: 'إذن التسليم جاهز',
    shipmentInfo: 'معلومات الشحنة',
    logisticsInfo: 'البيانات اللوجستية',
    driverAndVehicleInfo: 'بيانات النقل الداخلي',
    shippingLine: 'الخط الملاحي',
    bookingNo: 'رقم الحجز (Booking No)',
    containerSize: 'مقاس الحاوية',
    sealNo: 'رقم السيل (Seal No)',
    driverName: 'اسم السائق',
    driverPhone: 'هاتف السائق',
    truckPlate: 'رقم الشاحنة',
    trailerPlate: 'رقم المقطورة',
    addShipmentUpdate: 'إضافة ملاحظة / تحديث',
    enterUpdateMessage: 'اكتب تفاصيل التحديث هنا...',
    addUpdate: 'نشر التحديث',
    customsBroker: 'المخلص الجمركي',
    customsBrokerName: 'اسم المخلص',
    transportCompany: 'شركة النقل',
    importFromChat: 'استيراد من المحادثة (AI)',
    pasteChatHere: 'انسخ نص المحادثة (واتساب/إيميل) هنا ليتم استخراج البيانات تلقائياً...',
    parseChat: 'تحليل واستخراج البيانات',
    analyzing: 'جارٍ التحليل...',
    shipmentsFound: 'شحنات تم التعرف عليها',
    import: 'استيراد للجدول',
    saveAll: 'حفظ الكل',
    loadDataFromShipment: 'استيراد بيانات من شحنة سابقة',
    loadFromShipment: 'تحميل البيانات',
    shipmentNotFound: 'لم يتم العثور على شحنة برقم "{shipmentId}".',
    dataLoadedSuccess: 'تم استيراد بيانات الشحنة {shipmentId} بنجاح.',
    previewInEnglish: 'معاينة (إنجليزي)',
    previewInArabic: 'معاينة (عربي)',
    switchedToPreview: 'وضع المعاينة: {lang}',
    financeInfo: 'الإدارة المالية',
    cost: 'التكلفة التشغيلية',
    price: 'سعر البيع للعميل',
    profit: 'هامش الربح',
    editShipment: 'تعديل البيانات',
    saveChanges: 'حفظ التغييرات',
    certType: 'نوع الشهادة',
    certificateOfOrigin: 'شهادة المنشأ',
    phytosanitaryCertificate: 'شهادة صحة نباتية',
    leagueOfArabStates: 'جامعة الدول العربية',
    parties: 'الأطراف المعنية',
    exporterNameAddressCountry: '١. المصدر (الاسم، العنوان، الدولة)',
    importerNameAddressCountry: '٢. المستورد (الاسم، العنوان، الدولة)',
    producerAndAddress: 'بيانات المُنتِج',
    certNo: 'رقم الشهادة',
    portOfShipmentOptional: 'ميناء الشحن (اختياري)',
    vessel: 'اسم السفينة',
    blNo: 'رقم البوليصة',
    from: 'من (دولة المنشأ)',
    to: 'إلى (دولة المقصد)',
    date: 'التاريخ',
    commercialInvoiceNoAndDate: 'رقم وتاريخ الفاتورة التجارية',
    countryOfOrigin: 'دولة المنشأ',
    countryOfDestination: 'دولة الوصول',
    goodsAndMeasures: 'وصف البضائع والأوزان',
    number: 'رقم',
    numCategoriesOfParcels: 'عدد ونوع الطرود',
    grossMassKg: 'الوزن القائم (كجم)',
    statementByExporter: 'إقرار المصدر',
    certifyGoodsOfOrigin: 'تصديق الجهة المختصة',
    agriCertPlaceholder: 'قريباً: نموذج الشهادة الزراعية.',
    officialPreview: 'المعاينة الرسمية',
    enterDocumentData: 'إدخال البيانات',
    phytoNo: 'رقم الشهادة',
    phytoTo: '١. إلى منظمة وقاية النباتات في',
    phytoExporter: '٢. اسم وعنوان المصدر',
    phytoConsignee: '٣. اسم وعنوان المستلم',
    phytoConveyance: '٤. وسيلة النقل المصرح بها',
    phytoEntryPoint: '٥. نقطة الدخول المصرح بها',
    phytoPlaceOfOrigin: '٦. مكان المنشأ',
    phytoDistinguishingMarks: '٧. العلامات المميزة',
    phytoNumAndDesc: '٨. عدد وصف الطرود',
    phytoNameOfProduce: '٩. اسم المنتج والكمية المصرح بها',
    phytoBotanicalName: '١٠. الاسم النباتي',
    phytoCertificationText: '١١. نص الشهادة',
    phytoTreatment: '١٢. المعالجة',
    phytoChemical: '١٣. المادة الكيميائية',
    phytoConcentration: '١٤. التركيز',
    phytoDurationTemp: '١٥. المدة ودرجة الحرارة',
    phytoAddInfo: '١٦. معلومات إضافية',
    phytoAddDeclaration: '١٧. إقرار إضافي',
    phytoInspectionDate: '١٨. تاريخ الفحص',
    phytoIssueDate: '١٩. تاريخ الإصدار',
    phytoIssuePlace: '٢٠. مكان الإصدار',
    phytoInspectorName: '٢١. اسم المفتش',
    phytoAuthOfficerName: '٢٢. اسم المسؤول المعتمد',
    phytoPortOfLoading: '٢٣. ميناء التحميل',
    phytoStamp: '٢٤. ختم المنظمة',
    phytoSignature: '٢٥. توقيع المسؤول',
    routePlannerDesc: 'مستشار ملاحي ذكي يحلل المخاطر، الطقس، والتكلفة لاقتراح المسار الأمثل.',
    hsCodeFinderDesc: 'محرك بحث متطور يعالج الأوصاف التجارية ويطابقها مع التعريفة الجمركية.',
    invoiceGeneratorDesc: 'نظام متكامل لإصدار الفواتير وقوائم التعبئة المتوافقة مع البنوك والجمارك.',
    shippingFormsDesc: 'نماذج جاهزة لإقرارات الشحن (Shipping Declarations) بصيغ رسمية.',
    shipmentTrackerDesc: 'تتبع لحظي لحالة الشحنة من المصنع وحتى وصولها للمستودع.',
    documentEditorDesc: 'محرر مرئي لشهادات المنشأ والشهادات الزراعية (EUR.1, COMESA).',
    pricingSubtitle: 'باقات مصممة لتناسب حجم أعمالك.',
    monthlyPlan: 'اشتراك شهري',
    yearlyPlan: 'اشتراك سنوي',
    monthlyPrice: '٢٥٠',
    yearlyPrice: '٢٤٠٠',
    currency: 'ج.م',
    perMonth: '/شهر',
    perYear: '/سنة',
    savePrice: 'وفر ٢٠٪',
    billedMonthly: 'يتم الدفع شهرياً',
    billedYearly: 'دفع مرة واحدة سنوياً',
    planFeatures: 'مميزات الباقة:',
    feature1: 'تخطيط مسارات غير محدود',
    feature2: 'بحث متقدم في البنود الجمركية',
    feature3: 'إصدار وتصدير المستندات',
    feature4: 'نظام تتبع الشحنات الكامل',
    feature5: 'الوصول الكامل لدليل الشركات',
    mostPopular: 'الأكثر طلباً',
    tariffItem: 'البند الجمركي',
    originCriterion: 'معيار المنشأ',
    remarks: 'ملاحظات',
    cumulationApplied: 'تراكم المنشأ مطبق',
    issuedRetrospectively: 'صدرت بأثر رجعي',
    duplicate: 'نسخة بدل فاقد',
    transportDetails: 'تفاصيل النقل',
    previewSettings: 'إعدادات الطباعة',
    fontSize: 'حجم الخط (pt)',
    pageWidth: 'عرض الصفحة (مم)',
    pageHeight: 'ارتفاع الصفحة (مم)',
    resetSettings: 'استعادة الافتراضي',
    requiredField: 'هذا الحقل مطلوب',
    invalidEmail: 'البريد الإلكتروني غير صحيح',
    atLeastOnePort: 'يرجى إدخال ميناء واحد على الأقل',
    searchShipmentsPlaceholder: 'بحث برقم الحاوية، البوليصة، أو اسم العميل...',
    filterByDate: 'تصفية حسب التاريخ',
    allDates: 'الكل',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    // Document Formatting
    formatting: 'تنسيق النص',
    fontSizeLabel: 'حجم الخط',
    alignmentLabel: 'المحاذاة',
    increaseFont: 'تكبير',
    decreaseFont: 'تصغير',
    alignLeft: 'يسار',
    alignCenter: 'وسط',
    alignRight: 'يمين',
    // Knowledge and Directory
    knowledgeSectionTitle: 'قاعدة المعرفة اللوجستية',
    knowledgeSectionDesc: 'المصدر الأول للمعلومات الموثوقة: قوانين، إجراءات، وأخبار تهم كل محترف في المجال.',
    directorySectionTitle: 'دليل الشركات الموثوقة',
    directorySectionDesc: 'شبكة مختارة بعناية من مقدمي الخدمات اللوجستية، مصنفة حسب الكفاءة والسمعة.',
    knowledgeCard1Title: 'حالة الموانئ',
    knowledgeCard1Desc: 'تحديثات حية عن الازدحام، الطقس، وحالة العمل في الموانئ العربية.',
    knowledgeCard2Title: 'دليل الإجراءات',
    knowledgeCard2Desc: 'شرح مفصل لخطوات التخليص الجمركي في مصر، السعودية، والإمارات.',
    knowledgeCard3Title: 'التكنولوجيا والابتكار',
    knowledgeCard3Desc: 'كيف تغير التكنولوجيا وجه الشحن البحري؟ مقالات تحليلية.',
    directoryCard1Title: 'خطوط الشحن',
    directoryCard1Desc: 'وكلاء الخطوط الملاحية العالمية وجداول إبحارها.',
    directoryCard2Title: 'وكلاء الشحن',
    directoryCard2Desc: 'شركات Forwarding تقدم حلولاً متكاملة من الباب للباب.',
    directoryCard3Title: 'التخليص والنقل',
    directoryCard3Desc: 'وسطاء جمركيون وشركات نقل بري معتمدة.',
    // Shipping Forms Specific
    cityIn: 'مكان الإصدار',
    freightPayableAt: 'مكان دفع النولون',
    numberOfOriginalBl: 'عدد النسخ الأصلية',
    numberOfCopyBl: 'عدد الصور',
    netWeightKgs: 'الوزن الصافي (KGS)',
    grossWeightKgs: 'الوزن القائم (KGS)',
    footerSignature: 'التوقيع والختم',
    vesselNameForm: 'اسم السفينة',
    // Profile - Sidebar & Settings
    notifications: 'التنبيهات',
    helpAndSupport: 'المساعدة',
    security: 'أمان الحساب',
    notificationsSettings: 'إعدادات التنبيهات',
    emailNotifications: 'رسائل البريد الإلكتروني',
    smsNotifications: 'الرسائل النصية (SMS)',
    appUpdates: 'تحديثات النظام',
    faqs: 'الأسئلة الشائعة',
    contactSupport: 'الدعم الفني',
    receiveEmails: 'استلام تنبيهات عن حالة الشحنات عبر البريد',
    receiveSms: 'استلام تنبيهات عاجلة عبر SMS',
    receiveAppUpdates: 'أخبرني بالمميزات الجديدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsAndConditions: 'شروط الاستخدام',
    commonQuestions: 'إجابات على استفساراتك حول الاشتراكات والخدمات.',
    reachSupportTeam: 'فريقنا متاح لمساعدتك على مدار الساعة.',
    legalInformation: 'المعلومات القانونية.',
    dataProtection: 'كيف نحمي بياناتك.',
    // New Customs Expense Terms ARABIC
    operationNumber: 'رقم العملية (Operation No)',
    certificateNumber: 'رقم الشهادة الجمركية',
    agriculturalInspection: 'رسوم فحص زراعي',
    foodSafety: 'هيئة سلامة الغذاء',
    nathria: 'نثريات وإكراميات',
    mashal: 'رسوم مشال / عمالة',
    officialReceipts: 'إيصالات رسمية',
    clearanceFees: 'أتعاب التخليص',
    doorInspection: 'كشف ومعاينة',
    expensesBreakdown: 'تحليل المصروفات',
    printMode: 'خيارات الطباعة',
    fullDocument: 'طباعة المستند كامل',
    dataOnly: 'طباعة البيانات فقط',
    margins: 'ضبط الهوامش',
    marginTop: 'هامش علوي',
    marginLeft: 'هامش أيسر',
    baseFontSize: 'حجم الخط الأساسي',
    uploadPhoto: 'تغيير الصورة',
    companyDetails: 'بيانات الشركة',
    securitySettings: 'كلمة المرور والأمان',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    // Keys for Sidebar & Author Info
    youMightLike: 'مقالات مقترحة لك',
    weeklyLogisticsBrief: 'النشرة اللوجستية الأسبوعية',
    getMarketUpdates: 'اشترك الآن لتصلك أهم تحديثات السوق وأسعار الشحن.',
    editorialTeam: 'فريق تحرير المنصة',
    marketIntelligence: 'قسم ذكاء الأسواق',
  },
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const [theme, setTheme] = useState<Theme>('light');

  useEffect(() => {
    const persistedTheme = window.localStorage.getItem('theme') as Theme | null;
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    
    if (persistedTheme) {
      setTheme(persistedTheme);
    } else {
      setTheme(systemPrefersDark ? 'dark' : 'light');
    }
  }, []);

  useEffect(() => {
      document.documentElement.setAttribute('data-theme', theme);
      if (theme === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
      window.localStorage.setItem('theme', theme);
  }, [theme]);


  const dir = useMemo(() => (language === 'ar' ? 'rtl' : 'ltr'), [language]);
  
  document.documentElement.lang = language;
  document.documentElement.dir = dir;

  const t = useCallback((key: string, replacements: Record<string, string> = {}): string => {
    let translation = (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
    Object.keys(replacements).forEach(placeholder => {
        translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
    });
    return translation;
  }, [language]);

  const value: LocalizationContextType = {
    language,
    setLanguage,
    t,
    dir,
    theme,
    setTheme,
  };

  return React.createElement(
    LocalizationContext.Provider,
    { value: value },
    children
  );
};

export const useLocalization = (): LocalizationContextType => {
  const context = useContext(LocalizationContext);
  if (context === undefined) {
    throw new Error('useLocalization must be used within an AppProvider');
  }
  return context;
};
